### ISSUE TITLE
Dell: System freeze on XPS 13 (9310) at decompressing stage.

### ISSUE THREAD

**Issue by dguglielmi** [fwupd/fwupd#5668]
**Describe the bug**
Update from 3.12.1 to 3.13.1 freeze the system at [Decompressing].... stage on Gentoo Linux

**Steps to Reproduce**
1 - fwupmgr update

Devices with no available firmware updates: 
 • TPM 2.0
 • UEFI Device Firmware
 • UEFI Device Firmware
Devices with the latest available firmware version:
 • Package level of Dell dock
 • RTS5413 in Dell dock
 • RTS5487 in Dell dock
 • VMM5331 in Dell dock
 • WD19TB
 • KXG60PNV2T04 NVMe KIOXIA 2048GB
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade System Firmware from 3.12.1 to 3.13.1?                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release fixes the following issues:                              ║
║                                                                              ║
║ • Improved the stability of the system.                                      ║
║                                                                              ║
║ XPS 13 9310 must remain plugged into a power source for the duration of the  ║
║ update to avoid damage.                                                      ║
╚══════════════════════════════════════════════════════════════════════════════╝
Perform operation? [Y|n]: Y

Freeze the entire system second after, need to hard reboot the system

**Expected behavior**
Update to 3.13.1

**fwupd version information**
Please provide the version of the daemon and client.

```shell
fwupdmgr --version
compile   org.freedesktop.fwupd         1.8.13
compile   com.hughsie.libxmlb           0.3.10
compile   com.hughsie.libjcat           0.1.12
runtime   org.freedesktop.fwupd-efi     1.0
compile   org.freedesktop.gusb          0.4.5
runtime   com.hughsie.libjcat           0.1.12
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.4.5
runtime   org.kernel                    6.1.19-gentoo
runtime   org.freedesktop.fwupd         1.8.13

```

Installed by portage and I try master version compiled from sources

<details>

<summary>**fwupd device information**</summary>

Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices
Dell Inc. XPS 13 9310
│
├─WD19TB:
│ │   Device ID:          570867f4ddda9915445da59bd85cd0e0e507270e
│ │   Summary:            High performance dock
│ │   Current version:    01.01.00.03
│ │   Vendor:             Dell Inc. (USB:0x413C)
│ │   Install Duration:   1 minute
│ │   Serial Number:      2W49523/3178963064766279
│ │   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
│ │   Device Flags:       • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │ 
│ ├─Package level of Dell dock:
│ │     Device ID:        073624c16dd99abe01ba1da223a70321e4f29beb
│ │     Summary:          A representation of dock update status
│ │     Current version:  01.00.25.01
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 5 seconds
│ │     GUIDs:            d8927ff5-a5b2-5618-848b-8e8bfb75b66f
│ │                       8ceeeffd-51b6-580c-9b75-69143227aff8 ← USB\VID_413C&PID_B06E&hub&status
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │   
│ ├─RTS5413 in Dell dock:
│ │     Device ID:        0acceea54e71c4d8002593822afe0f4705616613
│ │     Summary:          USB 3.1 Generation 1 Hub
│ │     Current version:  01.21
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 14 seconds
│ │     GUIDs:            b27d25f1-019d-5718-b41a-02ddaefe5577 ← USB\VID_413C&PID_B06F
│ │                       86fb40c0-8bf5-5a8b-a4ad-3156cf6bfaf4 ← USB\VID_413C&PID_B06F&REV_0101
│ │                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ← USB\VID_413C&PID_B06F&hub
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   
│ ├─RTS5487 in Dell dock:
│ │     Device ID:        96969b82d977fdcbf607df084ef0dcf10119409b
│ │     Summary:          USB 3.1 Generation 2 Hub
│ │     Current version:  01.47
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 3 seconds
│ │     GUIDs:            acfcd89b-105d-55b9-b85b-08bf8508f38c ← USB\VID_413C&PID_B06E
│ │                       707c63d2-e597-5c40-84db-9b1bb4c48d96 ← USB\VID_413C&PID_B06E&REV_0101
│ │                       568ffa1e-a0db-5287-9ea3-872b60f7730b ← USB\VID_413C&PID_B06E&hub
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   
│ ├─VMM5331 in Dell dock:
│ │     Device ID:        228ac6846b64d532dd1ea1b7e651e8f5f55fbc34
│ │     Summary:          Multi Stream Transport controller
│ │     Current version:  05.06.03
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 6 minutes
│ │     GUID:             89fec0b6-6b76-5008-b82c-5e5c6c164007 ← MST-panamera-vmm5331-259
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │   
│ └─Thunderbolt controller in Dell dock:
│       Device ID:        0126762618040732965b9e38a4bc1a1af31bc087
│       Summary:          Thunderbolt controller
│       Current version:  60.00
│       Vendor:           Dell Inc. (THUNDERBOLT:0x00D4, TBT:0x00D4)
│       Install Duration: 22 seconds
│       GUIDs:            08a8c886-2818-544c-b1a3-588eb07ae487 ← THUNDERBOLT\VEN_00D4&DEV_B070
│                         48711a14-0aaa-55b8-a17f-f7c494b318c6 ← THUNDERBOLT\VEN_00D4&DEV_B070&REV_00
│                         c94770ca-1773-592c-b20a-e87243bc7cd0 ← TBT-00d4b070
│                         d9d01d94-4749-58f4-b318-87cb92251fdb ← TBT-00d4b070-controller1-1
│       Device Flags:     • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Install to parent device first
│                         • Device stages updates
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│     
├─Unknown Device:
│     Device ID:          63223cc2d1b0b8d4c45ef8cedcb1f45315d3ff20
│     GUID:               ca5c154c-a46a-59d8-bf77-0ca40522cc85 ← GPIO\ID_INT34C5:00
│   
├─11th Gen Intel Core™ i7-1165G7 @ 2.80GHz:
│ │   Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│ │   Current version:    0x000000a6
│ │   Vendor:             Intel
│ │   GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│ │                       30249f37-d140-5d3e-9319-186b1bd5cac3 ← CPUID\PRO_0&FAM_06
│ │                       2347ad97-b545-5bae-b6b3-b70a9553cbba ← CPUID\PRO_0&FAM_06&MOD_8C
│ │                       1df99df5-22f4-5505-98cc-22dcc53b132a ← CPUID\PRO_0&FAM_06&MOD_8C&STP_1
│ │   Device Flags:       • Internal device
│ │ 
│ ├─USB4 host controller:
│ │     Device ID:        a97b1e4096d98df75429ed41497676074a47354b
│ │     Summary:          Unmatched performance for high-speed I/O
│ │     GUID:             e72e778e-94f7-5ed2-b560-1c1262ee217c ← TBT-fixed
│ │     Device Flags:     • Internal device
│ │                       • System requires external power source
│ │                       • Signed Payload
│ │   
│ └─USB4 host controller:
│       Device ID:        d3c1b4ceb03ba8176446925ca14ffe0c1baed729
│       Summary:          Unmatched performance for high-speed I/O
│       GUID:             e72e778e-94f7-5ed2-b560-1c1262ee217c ← TBT-fixed
│       Device Flags:     • Internal device
│                         • System requires external power source
│                         • Signed Payload
│     
├─KXG60PNV2T04 NVMe KIOXIA 2048GB:
│     Device ID:          c430a03ca2a65dfe2412ff950c79c51f6aec1317
│     Summary:            NVM Express solid state drive
│     Current version:    10704104
│     Vendor:             Toshiba Corporation (NVME:0x1179)
│     Serial Number:      804F70ABFSH1
│     GUIDs:              73a0c81f-2555-56a5-bb6a-c2aeab2213d1 ← STORAGE-DELL-108638
│                         558810bc-de64-11e8-9f32-f2801f1b9fd1
│     Device Flags:       • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Signed Payload
│   
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    3.12.1
│ │   Minimum Version:    3.12.1
│ │   Vendor:             Dell (DMI:Dell Inc.)
│ │   Update State:       Success
│ │   GUIDs:              cfb08d7c-8d3d-41b1-846b-48f634dfac9d
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ ├─BootGuard Configuration:
│ │     Device ID:        b0d4430dfa6bde9f0c22680df36dbc8c15c80753
│ │     Current version:  20
│ │     Vendor:           Intel Corporation (MEI:0x8086)
│ │     GUIDs:            dd17041c-09ea-4b17-a271-5b989867ec65
│ │                       f18c7464-aa01-5b3d-bd4f-6623597d0f70 ← MEI\VEN_8086&DEV_A0E0
│ │                       395a4458-f3a4-54b5-9947-e8b069f33c31 ← MEI\VEN_8086&DEV_A0E0&REV_20
│ │                       9aac74f6-7b24-5601-835e-621220a654ca ← MEI\VEN_8086&DEV_A0E0&SUBSYS_10280991
│ │                       b51070a3-9cba-51a8-b3f4-e6003d05413a ← MEI\VEN_8086&DEV_A0E0&SUBSYS_10280991&REV_20
│ │     Device Flags:     • Internal device
│ │   
│ ├─UEFI Platform Key:
│ │     Device ID:        6924110cde4fa051bfdc600a60620dc7aa9d3c6a
│ │     Summary:          Dell Inc. Platform Key
│ │     Vendor:           Dell Inc.
│ │     GUID:             5f7cc4ea-9f7a-5c5f-b535-dfbcc73f5ba6 ← UEFI\CRT_2493B118EABD632FD3BA49C333A8329B1982E872
│ │   
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  217
│       Minimum Version:  217
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            00fe3755-a4d8-5ef7-ba5f-47979fbb3423 ← UEFI\CRT_E28D59CA489BD2AD580F2EA5D62D6A29BB9C02AE5A818434A37DA7FC11DFF9E9
│                         4a6cd2cb-8741-5257-9d1f-89a275dacca7 ← UEFI\CRT_E28D59CA489BD2AD580F2EA5D62D6A29BB9C02AE5A818434A37DA7FC11DFF9E9&ARCH_X64
│                         c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
│     
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Current version:    1.257.0.0
│     Vendor:             ST Microelectronics (TPM:STM)
│     GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│                         84df3581-f896-54d2-bd1a-372602f04c32 ← TPM\VEN_STM&DEV_0001
│                         bfaed10a-bbc1-525b-a329-35da2f63e918 ← TPM\VEN_STM&MOD_
│                         70b7b833-7e1a-550a-a291-b94a12d0f319 ← TPM\VEN_STM&DEV_0001&VER_2.0
│                         06f005e9-cb62-5d1a-82d9-13c534c53c48 ← TPM\VEN_STM&MOD_&VER_2.0
│     Device Flags:       • Internal device
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device can recover flash failures
│                         • Full disk encryption secrets may be invalidated when updating
│                         • Signed Payload
│   
├─TPM 2.0:
│     Device ID:          a3487e128cf1413519bce8e9a1ab3f5981e61458
│     Summary:            UEFI ESRT device
│     Current version:    0.1.1.1
│     Vendor:             Dell Inc. (PCI:0x1028)
│     Update State:       Success
│     GUIDs:              1c510e19-0b20-5a48-aa73-cba9daabdead ← 0991-2.0
│                         ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│                         73730635-f6c2-53da-9df2-948bb5ac1022 ← DELL-TPM-2.0-STM-
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│   
├─TigerLake-LP GT2 [Iris Xe Graphics]:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    01
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              54ff3ed7-1ea3-5279-975f-93c13bf2aa53 ← PCI\VEN_8086&DEV_9A49
│                         3c11d563-4f83-5bd1-8369-75359ea6b6f6 ← PCI\VEN_8086&DEV_9A49&REV_01
│                         ce09e928-da40-5d4b-b881-986f41632a37 ← PCI\VEN_8086&DEV_9A49&SUBSYS_10280991
│                         7ad6854a-8a22-543c-a31d-9d8b5c66bd2b ← PCI\VEN_8086&DEV_9A49&SUBSYS_10280991&REV_01
│                         06f2a40f-75b6-5238-9fac-71ea35045c1c ← PCI\VEN_8086&DEV_9A49&REV_00
│                         52eb8ce3-53ee-55ad-9faf-220a17b4ae4d ← PCI\VEN_8086&DEV_9A49&SUBSYS_10280991&REV_00
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
├─UEFI Device Firmware:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    164
│     Minimum Version:    164
│     Vendor:             DMI:Dell Inc.
│     Update State:       Success
│     GUID:               176e090d-0ddb-495e-8173-bc998ccfecd0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
└─UEFI Device Firmware:
      Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
      Summary:            UEFI ESRT device
      Current version:    275792132
      Minimum Version:    275792132
      Vendor:             DMI:Dell Inc.
      Update State:       Success
      GUID:               558810bc-de64-11e8-9f32-f2801f1b9fd1
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
    

```

</details>

**System UEFI configuration**
Please provide the output of the following commands:

```shell
efibootmgr -v
BootCurrent: 0000
Timeout: 2 seconds
BootOrder: 0000,0001,0002,0003
Boot0000* Gentoo Linux	PciRoot(0x0)/Pci(0xe,0x0)/NVMe(0x1,8C-E3-8E-05-00-3E-E6-D8)/HD(1,GPT,6ebe1aeb-5c72-423b-a1c0-5a01bbcb91de,0x800,0x79800)/File(\EFI\gentoo\shimx64.efi)
      dp: 02 01 0c 00 d0 41 03 0a 00 00 00 00 / 01 01 06 00 00 0e / 03 17 10 00 01 00 00 00 8c e3 8e 05 00 3e e6 d8 / 04 01 2a 00 01 00 00 00 00 08 00 00 00 00 00 00 00 98 07 00 00 00 00 00 eb 1a be 6e 72 5c 3b 42 a1 c0 5a 01 bb cb 91 de 02 02 / 04 04 34 00 5c 00 45 00 46 00 49 00 5c 00 67 00 65 00 6e 00 74 00 6f 00 6f 00 5c 00 73 00 68 00 69 00 6d 00 78 00 36 00 34 00 2e 00 65 00 66 00 69 00 00 00 / 7f ff 04 00
Boot0001* Gentoo Linux Unsecure	HD(1,GPT,6ebe1aeb-5c72-423b-a1c0-5a01bbcb91de,0x800,0x79800)/File(\EFI\gentoo\grubx64.efi)
      dp: 04 01 2a 00 01 00 00 00 00 08 00 00 00 00 00 00 00 98 07 00 00 00 00 00 eb 1a be 6e 72 5c 3b 42 a1 c0 5a 01 bb cb 91 de 02 02 / 04 04 34 00 5c 00 45 00 46 00 49 00 5c 00 67 00 65 00 6e 00 74 00 6f 00 6f 00 5c 00 67 00 72 00 75 00 62 00 78 00 36 00 34 00 2e 00 65 00 66 00 69 00 00 00 / 7f ff 04 00
Boot0002* UEFI RST KXG60PNV2T04 NVMe KIOXIA 2048GB 804F70ABFSH1 	PciRoot(0x0)/Pci(0xe,0x0)/NVMe(0x1,8C-E3-8E-05-00-3E-E6-D8)/HD(1,GPT,6ebe1aeb-5c72-423b-a1c0-5a01bbcb91de,0x800,0x79800)/File(\EFI\Boot\BootX64.efi){auto_created_boot_option}
      dp: 02 01 0c 00 d0 41 03 0a 00 00 00 00 / 01 01 06 00 00 0e / 03 17 10 00 01 00 00 00 8c e3 8e 05 00 3e e6 d8 / 04 01 2a 00 01 00 00 00 00 08 00 00 00 00 00 00 00 98 07 00 00 00 00 00 eb 1a be 6e 72 5c 3b 42 a1 c0 5a 01 bb cb 91 de 02 02 / 04 04 30 00 5c 00 45 00 46 00 49 00 5c 00 42 00 6f 00 6f 00 74 00 5c 00 42 00 6f 00 6f 00 74 00 58 00 36 00 34 00 2e 00 65 00 66 00 69 00 00 00 / 7f ff 04 00
    data: 4e ac 08 81 11 9f 59 4d 85 0e e2 1a 52 2c 59 b2
Boot0003* Linux Firmware Updater	HD(1,GPT,6ebe1aeb-5c72-423b-a1c0-5a01bbcb91de,0x800,0x79800)/File(\EFI\gentoo\fwupdx64.efi)
      dp: 04 01 2a 00 01 00 00 00 00 08 00 00 00 00 00 00 00 98 07 00 00 00 00 00 eb 1a be 6e 72 5c 3b 42 a1 c0 5a 01 bb cb 91 de 02 02 / 04 04 36 00 5c 00 45 00 46 00 49 00 5c 00 67 00 65 00 6e 00 74 00 6f 00 6f 00 5c 00 66 00 77 00 75 00 70 00 64 00 78 00 36 00 34 00 2e 00 65 00 66 00 69 00 00 00 / 7f ff 04 00
```

```shell
efivar -l | grep fw
(empty output)
```

```shell
tree /boot
/boot
├── boot -> .
├── config-6.1.12-gentoo
├── config-6.1.19-gentoo
├── efi
│   └── EFI
│       ├── BOOT
│       │   └── BOOTX64.EFI
│       ├── dell
│       │   ├── bios
│       │   │   └── recovery
│       │   │       ├── BIOS_CUR.rcv
│       │   │       └── BIOS_PRE.rcv
│       │   └── logs
│       │       ├── diags_current.xml
│       │       └── diags_previous.xml
│       └── gentoo
│           ├── fwupdx64.efi
│           ├── grubx64.efi
│           ├── mmx64.efi
│           └── shimx64.efi
├── grub
│   ├── grub.cfg
│   └── grubenv
├── initramfs-6.1.12-gentoo.img
├── initramfs-6.1.19-gentoo.img
├── lost+found
├── System.map-6.1.12-gentoo
├── System.map-6.1.19-gentoo
├── vmlinuz-6.1.12-gentoo
└── vmlinuz-6.1.19-gentoo

11 directories, 19 files

```

**Additional questions**

- Operating system and version: Gentoo Linux
- Have you tried rebooting? Yes, multiple time
- Is this a regression? Yes
- Are you using an NVMe disk? Yes
- Is secure boot enabled? Yes
- Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS? No

**Comment by hughsie** [comment]
A dufe of https://github.com/fwupd/fwupd/issues/5656 perhaps?

**Comment by dguglielmi** [comment]
I don't know if it's related to that issue specifically but the interesting part is that if I use 1.8.13, the fwupd service crash with:

`
Mar 30 22:29:25 xps13-9310 systemd[1]: Started fwupd.service.
Mar 30 22:29:38 xps13-9310 fwupd[2968]: double free or corruption (fasttop)
Mar 30 22:29:38 xps13-9310 systemd[1]: fwupd.service: Main process exited, code=dumped, status=6/ABRT
Mar 30 22:29:38 xps13-9310 systemd[1]: fwupd.service: Failed with result 'core-dump'.
`
but the system don't freeze at all

If I use my own compiled version from master I got:

`
fwupdmgr update 
Devices with no available firmware updates: 
 • TPM 2.0
 • UEFI Device Firmware
 • UEFI Device Firmware
Devices with the latest available firmware version:
 • KXG60PNV2T04 NVMe KIOXIA 2048GB
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade System Firmware from 3.12.1 to 3.13.1?                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release fixes the following issues:                              ║
║                                                                              ║
║ • Improved the stability of the system.                                      ║
║                                                                              ║
║ XPS 13 9310 must remain plugged into a power source for the duration of the  ║
║ update to avoid damage.                                                      ║
╚══════════════════════════════════════════════════════════════════════════════╝
Perform operation? [Y|n]: Y
Decompressing…           [                                       ]
`
Then the system is completely freeze (local session + ssh session). Nothing in the journal.

**Comment by hughsie** [comment]
I've just released 1.8.14 -- can you try that please.

**Comment by dguglielmi** [comment]
Same issue with 1.8.14. I upgraded libjcat to 0.1.13, libxmlb to 0.3.11. Give a  try with SB disabled + "Allow firmware downgrade" in UEFI settings 
```
fwupdmgr update --version
compile   org.freedesktop.fwupd         1.8.14
compile   com.hughsie.libxmlb           0.3.11
compile   com.hughsie.libjcat           0.1.13
runtime   org.freedesktop.fwupd-efi     1.0
compile   org.freedesktop.gusb          0.4.5
runtime   com.hughsie.libjcat           0.1.13
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.4.5
runtime   org.kernel                    6.1.19-gentoo
runtime   org.freedesktop.fwupd         1.8.14
```

The host freeze at the same stage with 1.8.14

```
 fwupdmgr update --verbose
(fwupdmgr:8471): GLib-DEBUG: 13:27:33.746: setenv()/putenv() are not thread-safe and should not be used after threads are created
(pkttyagent:8473): GLib-GIO-DEBUG: 13:27:33.748: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(fwupdmgr:8471): GLib-GIO-DEBUG: 13:27:33.758: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.758: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.759: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.759: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.759: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: unwatch_fast: "/system/proxy/" (active: 0, establishing: 1)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: unwatch_fast: "/system/proxy/http/" (active: 0, establishing: 1)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: unwatch_fast: "/system/proxy/https/" (active: 0, establishing: 1)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: unwatch_fast: "/system/proxy/ftp/" (active: 0, establishing: 1)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: unwatch_fast: "/system/proxy/socks/" (active: 0, establishing: 1)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: watch_established: "/system/proxy/" (establishing: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: watch_established: "/system/proxy/http/" (establishing: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: watch_established: "/system/proxy/https/" (establishing: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: watch_established: "/system/proxy/ftp/" (establishing: 0)
(fwupdmgr:8471): dconf-DEBUG: 13:27:33.760: watch_established: "/system/proxy/socks/" (establishing: 0)
(fwupdmgr:8471): GLib-GIO-DEBUG: 13:27:33.767: _g_io_module_get_default: Found default implementation libproxy (GLibproxyResolver) for ‘gio-proxy-resolver’
(fwupdmgr:8471): GLib-GIO-DEBUG: 13:27:33.768: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(fwupdmgr:8471): Fwupd-DEBUG: 13:27:33.819: Emitting ::status-changed() [idle]
Devices with no available firmware updates: 
 • TPM 2.0
 • UEFI Device Firmware
 • UEFI Device Firmware
Devices with the latest available firmware version:
 • KXG60PNV2T04 NVMe KIOXIA 2048GB
(fwupdmgr:8471): FuMain-DEBUG: 13:27:33.832: current version is 10704104: 10704104=same
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade System Firmware from 3.12.1 to 3.13.1?                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release fixes the following issues:                              ║
║                                                                              ║
║ • Improved the stability of the system.                                      ║
║                                                                              ║
║ XPS 13 9310 must remain plugged into a power source for the duration of the  ║
║ update to avoid damage.                                                      ║
╚══════════════════════════════════════════════════════════════════════════════╝
Perform operation? [Y|n]: Y
Fwupd-INFO: 13:27:37.239: downloading https://fwupd.org/downloads/257e955cb1dc489d25f56e73645edd07774b1fc1f904fa13096b19a721d9e1b4-Dell_XPS_13_9310_U_System_BIOS_V3.13.1.cab
(fwupdmgr:8471): Fwupd-DEBUG: 13:27:37.242: Emitting ::status-changed() [downloading]
Downloading…             [                   -                   ]Fwupd-INFO: 13:27:37.999: download progress: 100%
Downloading…             [***************************************]Fwupd-INFO: 13:27:38.306: download progress: 0%
Downloading…             [  -                                    ]Fwupd-INFO: 13:27:38.381: download progress: 1%
Downloading…             [                                       ]Fwupd-INFO: 13:27:38.394: download progress: 2%
Downloading…             [                                       ]Fwupd-INFO: 13:27:38.399: download progress: 3%
Downloading…             [*                                      ]Fwupd-INFO: 13:27:38.405: download progress: 4%
Downloading…             [*                                      ]Fwupd-INFO: 13:27:38.409: download progress: 5%
Downloading…             [*                                      ]Fwupd-INFO: 13:27:38.413: download progress: 6%
Downloading…             [**                                     ]Fwupd-INFO: 13:27:38.418: download progress: 7%
Downloading…             [**                                     ]Fwupd-INFO: 13:27:38.422: download progress: 8%
Downloading…             [***                                    ]Fwupd-INFO: 13:27:38.426: download progress: 9%
Downloading…             [***                                    ]Fwupd-INFO: 13:27:38.430: download progress: 10%
Downloading…             [***                                    ]Fwupd-INFO: 13:27:38.434: download progress: 11%
Downloading…             [****                                   ]Fwupd-INFO: 13:27:38.438: download progress: 12%
Downloading…             [****                                   ]Fwupd-INFO: 13:27:38.443: download progress: 13%
Downloading…             [*****                                  ]Fwupd-INFO: 13:27:38.447: download progress: 14%
Downloading…             [*****                                  ]Fwupd-INFO: 13:27:38.451: download progress: 15%
Downloading…             [*****                                  ]Fwupd-INFO: 13:27:38.456: download progress: 16%
Downloading…             [******                                 ]Fwupd-INFO: 13:27:38.459: download progress: 17%
Downloading…             [******                                 ]Fwupd-INFO: 13:27:38.463: download progress: 18%
Downloading…             [*******                                ]Fwupd-INFO: 13:27:38.468: download progress: 19%
Downloading…             [*******                                ]Fwupd-INFO: 13:27:38.472: download progress: 20%
Downloading…             [*******                                ]Fwupd-INFO: 13:27:38.476: download progress: 21%
Downloading…             [********                               ]Fwupd-INFO: 13:27:38.480: download progress: 22%
Downloading…             [********                               ]Fwupd-INFO: 13:27:38.484: download progress: 23%
Downloading…             [********                               ]Fwupd-INFO: 13:27:38.488: download progress: 24%
Downloading…             [*********                              ]Fwupd-INFO: 13:27:38.493: download progress: 25%
Downloading…             [*********                              ]Fwupd-INFO: 13:27:38.497: download progress: 26%
Downloading…             [**********                             ]Fwupd-INFO: 13:27:38.501: download progress: 27%
Downloading…             [**********                             ]Fwupd-INFO: 13:27:38.505: download progress: 28%
Downloading…             [**********                             ]Fwupd-INFO: 13:27:38.510: download progress: 29%
Downloading…             [***********                            ]Fwupd-INFO: 13:27:38.513: download progress: 30%
Downloading…             [***********                            ]Fwupd-INFO: 13:27:38.517: download progress: 31%
Downloading…             [************                           ]Fwupd-INFO: 13:27:38.521: download progress: 32%
Downloading…             [************                           ]Fwupd-INFO: 13:27:38.525: download progress: 33%
Downloading…             [************                           ]Fwupd-INFO: 13:27:38.529: download progress: 34%
Downloading…             [*************                          ]Fwupd-INFO: 13:27:38.533: download progress: 35%
Downloading…             [*************                          ]Fwupd-INFO: 13:27:38.538: download progress: 36%
Downloading…             [**************                         ]Fwupd-INFO: 13:27:38.543: download progress: 37%
Downloading…             [**************                         ]Fwupd-INFO: 13:27:38.546: download progress: 38%
Downloading…             [**************                         ]Fwupd-INFO: 13:27:38.550: download progress: 39%
Downloading…             [***************                        ]Fwupd-INFO: 13:27:38.554: download progress: 40%
Downloading…             [***************                        ]Fwupd-INFO: 13:27:38.558: download progress: 41%
Downloading…             [***************                        ]Fwupd-INFO: 13:27:38.562: download progress: 42%
Downloading…             [****************                       ]Fwupd-INFO: 13:27:38.566: download progress: 43%
Downloading…             [****************                       ]Fwupd-INFO: 13:27:38.571: download progress: 44%
Downloading…             [*****************                      ]Fwupd-INFO: 13:27:38.574: download progress: 45%
Downloading…             [*****************                      ]Fwupd-INFO: 13:27:38.579: download progress: 46%
Downloading…             [*****************                      ]Fwupd-INFO: 13:27:38.583: download progress: 47%
Downloading…             [******************                     ]Fwupd-INFO: 13:27:38.587: download progress: 48%
Downloading…             [******************                     ]Fwupd-INFO: 13:27:38.591: download progress: 49%
Downloading…             [*******************                    ]Fwupd-INFO: 13:27:38.596: download progress: 50%
Downloading…             [*******************                    ]Fwupd-INFO: 13:27:38.599: download progress: 51%
Downloading…             [*******************                    ]Fwupd-INFO: 13:27:38.603: download progress: 52%
Downloading…             [********************                   ]Fwupd-INFO: 13:27:38.607: download progress: 53%
Downloading…             [********************                   ]Fwupd-INFO: 13:27:38.612: download progress: 54%
Downloading…             [*********************                  ]Fwupd-INFO: 13:27:38.616: download progress: 55%
Downloading…             [*********************                  ]Fwupd-INFO: 13:27:38.620: download progress: 56%
Downloading…             [*********************                  ]Fwupd-INFO: 13:27:38.624: download progress: 57%
Downloading…             [**********************                 ]Fwupd-INFO: 13:27:38.629: download progress: 58%
Downloading…             [**********************                 ]Fwupd-INFO: 13:27:38.632: download progress: 59%
Downloading…             [***********************                ]Fwupd-INFO: 13:27:38.636: download progress: 60%
Downloading…             [***********************                ]Fwupd-INFO: 13:27:38.640: download progress: 61%
Downloading…             [***********************                ]Fwupd-INFO: 13:27:38.646: download progress: 62%
Downloading…             [************************               ]Fwupd-INFO: 13:27:38.651: download progress: 63%
Downloading…             [************************               ]Fwupd-INFO: 13:27:38.654: download progress: 64%
Downloading…             [************************               ]Fwupd-INFO: 13:27:38.657: download progress: 65%
Downloading…             [*************************              ]Fwupd-INFO: 13:27:38.662: download progress: 66%
Downloading…             [*************************              ]Fwupd-INFO: 13:27:38.666: download progress: 67%
Downloading…             [**************************             ]Fwupd-INFO: 13:27:38.670: download progress: 68%
Downloading…             [**************************             ]Fwupd-INFO: 13:27:38.674: download progress: 69%
Downloading…             [**************************             ]Fwupd-INFO: 13:27:38.678: download progress: 70%
Downloading…             [***************************            ]Fwupd-INFO: 13:27:38.683: download progress: 71%
Downloading…             [***************************            ]Fwupd-INFO: 13:27:38.686: download progress: 72%
Downloading…             [****************************           ]Fwupd-INFO: 13:27:38.691: download progress: 73%
Downloading…             [****************************           ]Fwupd-INFO: 13:27:38.695: download progress: 74%
Downloading…             [****************************           ]Fwupd-INFO: 13:27:38.699: download progress: 75%
Downloading…             [*****************************          ]Fwupd-INFO: 13:27:38.704: download progress: 76%
Downloading…             [*****************************          ]Fwupd-INFO: 13:27:38.708: download progress: 77%
Downloading…             [******************************         ]Fwupd-INFO: 13:27:38.712: download progress: 78%
Downloading…             [******************************         ]Fwupd-INFO: 13:27:38.718: download progress: 79%
Downloading…             [******************************         ]Fwupd-INFO: 13:27:38.722: download progress: 80%
Downloading…             [*******************************        ]Fwupd-INFO: 13:27:38.726: download progress: 81%
Downloading…             [*******************************        ]Fwupd-INFO: 13:27:38.730: download progress: 82%
Downloading…             [*******************************        ]Fwupd-INFO: 13:27:38.734: download progress: 83%
Downloading…             [********************************       ]Fwupd-INFO: 13:27:38.738: download progress: 84%
Downloading…             [********************************       ]Fwupd-INFO: 13:27:38.743: download progress: 85%
Downloading…             [*********************************      ]Fwupd-INFO: 13:27:38.747: download progress: 86%
Downloading…             [*********************************      ]Fwupd-INFO: 13:27:38.751: download progress: 87%
Downloading…             [*********************************      ]Fwupd-INFO: 13:27:38.755: download progress: 88%
Downloading…             [**********************************     ]Fwupd-INFO: 13:27:38.760: download progress: 89%
Downloading…             [**********************************     ]Fwupd-INFO: 13:27:38.763: download progress: 90%
Downloading…             [***********************************    ]Fwupd-INFO: 13:27:38.767: download progress: 91%
Downloading…             [***********************************    ]Fwupd-INFO: 13:27:38.772: download progress: 92%
Downloading…             [***********************************    ]Fwupd-INFO: 13:27:38.775: download progress: 93%
Downloading…             [************************************   ]Fwupd-INFO: 13:27:38.780: download progress: 94%
Downloading…             [************************************   ]Fwupd-INFO: 13:27:38.783: download progress: 95%
Downloading…             [*************************************  ]Fwupd-INFO: 13:27:38.788: download progress: 96%
Downloading…             [*************************************  ]Fwupd-INFO: 13:27:38.792: download progress: 97%
Downloading…             [*************************************  ]Fwupd-INFO: 13:27:38.796: download progress: 98%
Downloading…             [************************************** ]Fwupd-INFO: 13:27:38.799: download progress: 99%
Downloading…             [************************************** ]Fwupd-INFO: 13:27:38.804: download progress: 100%
(fwupdmgr:8471): Fwupd-DEBUG: 13:27:38.804: Emitting ::status-changed() [idle]
Fwupd-INFO: 13:27:38.804: status-code was 200
(fwupdmgr:8471): Fwupd-DEBUG: 13:27:38.915: Emitting ::status-changed() [decompressing]
Decompressing…           [***************************************](fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.352: Emitting ::status-changed() [waiting-for-auth]
Authenticating…          [ -                                     ](fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.364: Emitting ::status-changed() [device-busy]
Waiting…                 [ -                                     ](fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.364: Emitting ::device-changed(a45df35ac0e948ee180fe216a5f703f32dda163f)
(fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.364: Emitting ::device-changed(a45df35ac0e948ee180fe216a5f703f32dda163f)
(fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.371: Emitting ::device-changed(a45df35ac0e948ee180fe216a5f703f32dda163f)
(fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.371: Emitting ::device-changed(a45df35ac0e948ee180fe216a5f703f32dda163f)
(fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.374: Emitting ::status-changed() [device-write]
Writing…                 [                                       ](fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.374: Emitting ::status-changed() [device-restart]
Restarting device…       [                                       ](fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.374: Emitting ::status-changed() [device-write]
Writing…                 [                                       ](fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.374: Emitting ::status-changed() [scheduling]
Scheduling…              [                                       ](fwupdmgr:8471): Fwupd-DEBUG: 13:27:39.374: Emitting ::status-changed() [decompressing]
Decompressing…           [                                       ]
```

Unable to see/get kernel errors messages after the freeze.

**Comment by dguglielmi** [comment]
I've made some progress, and it's not specifically related to the Dell firmware update. I manually updated it from the Dell UEFI interface and I still have the same behavior (system freeze during decompression) with the Secure Boot upgrade dbx 217 -> 220

**Comment by dguglielmi** [comment]
Ok, I finally got It. The freezes on my system were visibly related to efivars files in /sys/firmware/efi/efivars/. I was able to reproduce a freeze by simply trying to add and/or modify boot entries order with efibootmgr.

Problem solved by purging /sys/firmware/efi/efivars/dump-type0* files.

**Comment by hughsie** [comment]
Do you know what created the /sys/firmware/efi/efivars/dump-type0 files?

**Comment by superm1** [comment]
Doesn't the kernel directly create those types of files when you have `CONFIG_EFI_PSTORE` set? The expectation is that they'll be cleared by userspace.

That's what systemd should have been doing; moving them to `/var/lib/systemd/pstore`

**Comment by dguglielmi** [comment]
Sadly I deleted the files without making a copy. There were about 20-30 (dump-type0-xxxx) files.

My kernel config for PSTORE is:

```
# grep PSTORE /boot/config-6.1.24-gentoo 
CONFIG_EFI_VARS_PSTORE=m
# CONFIG_EFI_VARS_PSTORE_DEFAULT_DISABLE is not set
# CONFIG_MTD_PSTORE is not set
CONFIG_CHROMEOS_PSTORE=m
CONFIG_PSTORE=y
CONFIG_PSTORE_DEFAULT_KMSG_BYTES=10240
CONFIG_PSTORE_DEFLATE_COMPRESS=y
# CONFIG_PSTORE_LZO_COMPRESS is not set
# CONFIG_PSTORE_LZ4_COMPRESS is not set
# CONFIG_PSTORE_LZ4HC_COMPRESS is not set
# CONFIG_PSTORE_842_COMPRESS is not set
# CONFIG_PSTORE_ZSTD_COMPRESS is not set
CONFIG_PSTORE_COMPRESS=y
CONFIG_PSTORE_DEFLATE_COMPRESS_DEFAULT=y
CONFIG_PSTORE_COMPRESS_DEFAULT="deflate"
# CONFIG_PSTORE_CONSOLE is not set
# CONFIG_PSTORE_PMSG is not set
# CONFIG_PSTORE_FTRACE is not set
CONFIG_PSTORE_RAM=m
CONFIG_PSTORE_ZONE=m
CONFIG_PSTORE_BLK=m
CONFIG_PSTORE_BLK_BLKDEV=""
CONFIG_PSTORE_BLK_KMSG_SIZE=64
CONFIG_PSTORE_BLK_MAX_REASON=2
```

If interested, I will take a look if that kind of files reappear and try to understand why and by what they are created.

**Comment by superm1** [comment]
Do you use systemd? Or something different?

**Comment by dguglielmi** [comment]
Yes, I use systemd.  /var/lib/systemd/pstore is empty. I don't remember disabling systemd-pstore unit but:

```
# systemctl status systemd-pstore.service
○ systemd-pstore.service - Platform Persistent Storage Archival
     Loaded: loaded (/usr/lib/systemd/system/systemd-pstore.service; disabled; preset: enabled)
     Active: inactive (dead)
       Docs: man:systemd-pstore(8)
```

Would you recommend enable the unit ?

**Comment by superm1** [comment]
Can you look at the logs for that unit? I think it just runs on boot.

**Comment by dguglielmi** [comment]
The logs are empty for now:

```
# journalctl -u systemd-pstore
-- No entries --
```

If I start the unit manually I got:

```
# systemctl start systemd-pstore
# journalctl -u systemd-pstore
May 15 23:28:23 xps13-9310 systemd[1]: systemd-pstore.service was skipped because of an unmet condition check (ConditionDirectoryNotEmpty=/sys/fs/pstore).
```
