### ISSUE TITLE
Building 1.9.6 version on openSUSE fails, because location of amdgpu_drm.h

### ISSUE THREAD

**Issue by weberhofer** [fwupd/fwupd#6266]
Building  version 1.9.6 on openSUSE Tumbleweed fails because the `amdgpu_drm.h` is located in `libdrm/amdgpu_drm.h` instead of  `drm/amdgpu_drm.h`.

The location is currently hardcoded in `meson.build` and `plugins/amd-gpu/fu-amd-gpu-device.c`.

Would be great, if the location could be made flexible.

**Comment by superm1** [comment]
Can you please share the specific build log with the failure?

We made some changes in main related to detection for that header, can you try building main too?

**Comment by superm1** [comment]
Actually I think I see a way to handle this more cleanly.  Can you please test that PR on top of main?

**Comment by superm1** [comment]
I realized that's completely wrong.  We're looking for **kernel headers** not **libdrm headers**; the stuff in main is as it's intended.  

```
/usr/include$ find -name "amdgpu_drm*.h"
./drm/amdgpu_drm.h
./libdrm/amdgpu_drm.h
```

Maybe you're missing kernel headers in your build process.

**Comment by dataCobra** [comment]
I'm trying to build and package fwupd 1.9.6 as well for voidlinux. We also use libdrm as the location.

To make sure these headers are correct I symlinked /usr/include/libdrm to /usr/include/drm and checked the tests.

**Comment by dataCobra** [comment]
I do have kernel-headers installed during installation.

If you mean the uapi drm headers they are located here on voidlinux:
`/usr/src/kernel-headers-6.5.7_1/include/uapi/drm/amdgpu_drm.h`

**Comment by superm1** [comment]
You couldn't build a kernel module against that directory though, that seems wrong.

It definitely shouldn't have uapi in the installed path.

For those headers Is there a missing symlink? Or missing install step?

**Comment by superm1** [comment]
If it helps on Debian and Ubuntu this is part of the `linux-libc-dev` package.
```
$ dpkg -S /usr/include/drm/amdgpu_drm.h
linux-libc-dev:amd64: /usr/include/drm/amdgpu_drm.h
```

**Comment by weberhofer** [comment]
I have included the patch in the, but it still fails; in `plugins/amd-gpu/fu-amd-gpu-device.c` you'll find
```c
#include <drm/amdgpu_drm.h>
```
which on openSUSE should be
```c
#include <libdrm/amdgpu_drm.h>
```
that is added to the build environment via `BuildRequires:  pkgconfig(libdrm)`.

**Comment by superm1** [comment]
@weberhofer please discard the patch.  It's wrong. 

You're pulling the wrong headers.  You need kernel headers not libdrm headers.

**Comment by Kerrung** [comment]
@superm1 I have the same problem on Arch Linux. And I have the linux-headers package installed. I tried building commit [2a8aec8384040ee8d29ced64bf31fedce62c054596](https://github.com/fwupd/fwupd/commit/2a8aec83840ee8d29ced64bf31fedce62c054596)

[A terminal log.txt](https://github.com/fwupd/fwupd/files/12921129/log.txt)
[meson-log.txt](https://github.com/fwupd/fwupd/files/12921159/meson-log.txt)
[PKGBUILD.zip](https://github.com/fwupd/fwupd/files/12921165/PKGBUILD.zip)
![Screenshot from 2023-10-17 00-47-01](https://github.com/fwupd/fwupd/assets/36989404/b2b5ae9a-fd27-4439-8102-42697af8303c)

**Comment by superm1** [comment]
@Kerrung can you please ping the owner for [linux-api-headers](https://archlinux.org/packages/core/any/linux-api-headers/) to look at this issue for Arch?  It seems like that's the package that should be carrying this header from the kernel but I don't see it.

**Comment by superm1** [comment]
@weberhofer looking at OpenSUSE, I think it should be coming through [linux-glibc-devel](https://software.opensuse.org/download.html?project=openSUSE%3AFactory&package=linux-glibc-devel).  Please check with the owner for this package.

**Comment by Kerrung** [comment]
> @Kerrung can you please ping the owner for [linux-api-headers](https://archlinux.org/packages/core/any/linux-api-headers/) to look at this issue for Arch? It seems like that's the package that should be carrying this header from the kernel but I don't see it.

The only thing I can do is write a bug report on the Arch bug tracker.

**Comment by Kerrung** [comment]
> @Kerrung can you please ping the owner for [linux-api-headers](https://archlinux.org/packages/core/any/linux-api-headers/) to look at this issue for Arch? It seems like that's the package that should be carrying this header from the kernel but I don't see it.

https://archlinux.org/packages/core/x86_64/linux-headers/
Or maybe this package is needed?

**Comment by superm1** [comment]
> https://archlinux.org/packages/core/x86_64/linux-headers/
> Or maybe this package is needed?

So that package does contain an `amdgpu_drm.h`, but it's not in any include path.

```
usr/lib/modules/6.5.7-arch1-1/build/include/uapi/drm/amdgpu_drm.h
```

I'm not sure how any software can be expected to discover it in a path like that.  It would mean that `/usr/lib/modules/6.5.7-arch1-1/build/include/uapi`  needs to be added into the search path.

**Comment by superm1** [comment]
@hughsie I guess reading through https://cgit.freedesktop.org/drm/libdrm/tree/include/drm/README it looks like the copy included in libdrm _is_ a kernel copy.  Maybe we should just duplicate it in fwupd too then.

**Comment by Kerrung** [comment]
> > https://archlinux.org/packages/core/x86_64/linux-headers/
> > Or maybe this package is needed?
> 
> So that package does contain an `amdgpu_drm.h`, but it's not in any include path.
> 
> ```
> usr/lib/modules/6.5.7-arch1-1/build/include/uapi/drm/amdgpu_drm.h
> ```
> 
> I'm not sure how any software can be expected to discover it in a path like that. It would mean that `/usr/lib/modules/6.5.7-arch1-1/build/include/uapi` needs to be added into the search path.

Can you fix it?

**Comment by superm1** [comment]
> @hughsie I guess reading through https://cgit.freedesktop.org/drm/libdrm/tree/include/drm/README it looks like the copy included in libdrm _is_ a kernel copy. Maybe we should just duplicate it in fwupd too then.

or we depend on `libdrm` (what my PR did).

Here's how libdrm does it.
1. They sync all the files here: https://gitlab.freedesktop.org/mesa/drm/-/tree/main/include/drm?ref_type=heads
2. They make a top level include: https://gitlab.freedesktop.org/mesa/drm/-/blob/main/meson.build?ref_type=heads#L284
3. They include it in the whole project build: https://gitlab.freedesktop.org/mesa/drm/-/blob/main/meson.build?ref_type=heads#L305

We can do the same, but it trips up our license and formatting checker, so we'd need to set the policy to ignore that directory.

**Comment by Kerrung** [comment]
@superm1 I just tried this https://github.com/fwupd/fwupd/pull/6269. There are changes. This time the compilation was at least able to start, but still ended up crashing. Here are the new logs.

[log.txt](https://github.com/fwupd/fwupd/files/12922239/log.txt)
[meson-log.txt](https://github.com/fwupd/fwupd/files/12922243/meson-log.txt)
[PKGBUILD.zip](https://github.com/fwupd/fwupd/files/12922247/PKGBUILD.zip)

**Comment by superm1** [comment]
Try with the new changes I just published.

**Comment by Kerrung** [comment]
> Try with the new changes I just published.

Now fixed. Thanks!

**Comment by Kerrung** [comment]
> Try with the new changes I just published.

@superm1 The compilation now works fine without crashing. But I still don't see my Radeon GPU in the list of devices displayed by FWUPD afterwards.

**Comment by superm1** [comment]
> > Try with the new changes I just published.
> 
> @superm1 The compilation now works fine without crashing. But I still don't see my Radeon GPU in the list of devices displayed by FWUPD afterwards.

What kernel version? Can you share output for 

sudo fwupdtool get-devices --verbose

**Comment by Kerrung** [comment]
> > > Try with the new changes I just published.
> > 
> > 
> > @superm1 The compilation now works fine without crashing. But I still don't see my Radeon GPU in the list of devices displayed by FWUPD afterwards.
> 
> What kernel version? Can you share output for
> 
> sudo fwupdtool get-devices --verbose

1) This version: https://archlinux.org/packages/core/x86_64/linux/

2) [log.txt](https://github.com/fwupd/fwupd/files/12922633/log.txt)

**Comment by superm1** [comment]
I see it listed in your log.

```
â”‚   
â”œâ”€D09001 Lexa XL A0 GDDR5 128bit 2GB 214e/300m:
â”‚     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
â”‚     Current version:    015.050.002.001.000000
â”‚     Vendor:             Advanced Micro Devices, Inc. [AMD/ATI] (PCI:0x1002, PCI:0x1022)
â”‚     GUIDs:              4daaf54e-4446-5b25-8979-7fc017051118 â† PCI\VEN_1002&DEV_699F
â”‚                         d2683e36-8462-55c4-9851-777449b36eda â† PCI\VEN_1002&DEV_699F&SUBSYS_10020B04
â”‚                         e4c836f2-91e6-5e6d-943e-7d35d4ed1472 â† AMD\xxx-xxx-xxx
â”‚     Device Flags:       â€¢ Cryptographic hash verification is available
```

**Comment by Kerrung** [comment]
> I see it listed in your log.
> 
> ```
> â”‚   
> â”œâ”€D09001 Lexa XL A0 GDDR5 128bit 2GB 214e/300m:
> â”‚     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
> â”‚     Current version:    015.050.002.001.000000
> â”‚     Vendor:             Advanced Micro Devices, Inc. [AMD/ATI] (PCI:0x1002, PCI:0x1022)
> â”‚     GUIDs:              4daaf54e-4446-5b25-8979-7fc017051118 â†� PCI\VEN_1002&DEV_699F
> â”‚                         d2683e36-8462-55c4-9851-777449b36eda â†� PCI\VEN_1002&DEV_699F&SUBSYS_10020B04
> â”‚                         e4c836f2-91e6-5e6d-943e-7d35d4ed1472 â†� AMD\xxx-xxx-xxx
> â”‚     Device Flags:       â€¢ Cryptographic hash verification is available
> ```

And how can I install firmware updates on my GPU?
sudo fwupdmgr update
It doesn't show this in the device list, at least devices not available for update.

`Devices with no available firmware updates: 
 • ADATA SX8200PNP
 • HD103SJ
 • HD204UI
 • PLEXTOR PX-128M5Pro
 • WDC WD6400AAKS-00A7B0
Devices with the latest available firmware version:
 • Unifying Receiver
 • Unifying Receiver`

**Comment by superm1** [comment]
Your GPU doesn't support updates, this is only for Navi 3x and newer.
