### ISSUE TITLE
dell_dock: device does not set FWUPD_REQUEST_FLAG_NON_GENERIC_MESSAGE

### ISSUE THREAD

**Issue by CragW** [fwupd/fwupd#6589]
**Describe the bug**
After the firmware is installed, a human unfriendly message was prompted to user while some critical errors are seen on the daemon side.

```
$ sudo ./dist/fwupd.sh
09:35:59.416 FuMain               Daemon ready for requests (locale en_US.UTF-8)
09:36:04.726 GLib-GObject         invalid cast from 'GUnixInputStream' to 'GSeekable'
09:36:04.726 GLib-GIO             g_seekable_can_seek: assertion 'G_IS_SEEKABLE (seekable)' failed
```

```
$ ./dist/fwupdmgr.sh install ~/Downloads/cab/b1275193349c3ebd1db3821462143ac859302afe3572060fab7ee4793b4892bd-DellDockFirmwareUpdateLinux_01.00.16.cab --allow-reinstall
WARNING: This package has not been validated, it may not work properly.
Decompressing…           [                                       ]
request org.freedesktop.fwupd.request.remove-replug is not a GENERIC_MESSAGE and the device does not set FWUPD_REQUEST_FLAG_NON_GENERIC_MESSAGE
```

**Steps to Reproduce**
1. build fwupd from source
2. launch the daemon
3. install firmware for dell dock

**Expected behavior**
No errors.

**fwupd version information**
```shell
$ ./dist/fwupdmgr.sh --version
compile   com.hughsie.libxmlb           0.3.6
compile   com.hughsie.libjcat           0.1.9
compile   org.freedesktop.fwupd         2.0.0
runtime   org.freedesktop.fwupd-efi     2.0.0
compile   org.freedesktop.gusb          0.3.10
runtime   org.freedesktop.gusb          0.3.10
runtime   org.freedesktop.fwupd         2.0.0
runtime   org.kernel                    6.5.0-1007-oem
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
source

<details>

<summary>**fwupd device information**</summary>

```shell
Idle…: 0%
[31m[1mWARNING[0m: This package has not been validated, it may not work properly.
Dell Inc. XPS 13 9310
│
├─WD22TB4:
│ │   Device ID:          26140adcae5d9ca71008259caf4bb8639005cfde
│ │   Summary:            High performance dock
│ │   Current version:    01.01.00.05
│ │   Vendor:             Dell Inc. (USB:0x413C)
│ │   Install Duration:   1 minute
│ │   Serial Number:      6R2X0L3/3107576664195875
│ │   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
│ │   Device Flags:       • Updatable
│ │                       • Device stages updates
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │ 
│ ├─Package level of Dell dock:
│ │     Device ID:        cc4b0e729e344517c4690908fe1b4aaadea014ac
│ │     Summary:          A representation of dock update status
│ │     Current version:  01.00.32.01
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 5 seconds
│ │     Update State:     Failed
│ │     Update Error:     [31m[1mrequest org.freedesktop.fwupd.request.remove-replug is not a GENERIC_MESSAGE and the device does not set FWUPD_REQUEST_FLAG_NON_GENERIC_MESSAGE[0m
│ │     Last modified:    2024-01-02 09:36
│ │     GUIDs:            af2a3b39-98c4-59a9-9cbe-a6909a7d14a2
│ │                       7fb217aa-2312-5c99-a853-56d865c76815 ← USB\VID_413C&PID_B06E&hub&salomon_mlk_status
│ │     Device Flags:     • Updatable
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │   
│ ├─RTS5413 in Dell dock:
│ │     Device ID:        9fd950f74258cf110cf0f8dc9291544d5195f96f
│ │     Summary:          USB 3.1 Generation 1 Hub
│ │     Current version:  01.21
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 14 seconds
│ │     GUIDs:            b27d25f1-019d-5718-b41a-02ddaefe5577 ← USB\VID_413C&PID_B06F
│ │                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ← USB\VID_413C&PID_B06F&hub
│ │     Device Flags:     • Updatable
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   
│ ├─RTS5487 in Dell dock:
│ │     Device ID:        59b1a6cbc5fbf891fbb85aac889b31cf93f30307
│ │     Summary:          USB 3.1 Generation 2 Hub
│ │     Current version:  01.49
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 3 seconds
│ │     GUIDs:            acfcd89b-105d-55b9-b85b-08bf8508f38c ← USB\VID_413C&PID_B06E
│ │                       568ffa1e-a0db-5287-9ea3-872b60f7730b ← USB\VID_413C&PID_B06E&hub
│ │     Device Flags:     • Updatable
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   
│ ├─VMM5331 in Dell dock:
│ │     Device ID:        e490d48c4b27154dd574a1c340f3a692f7eb052a
│ │     Summary:          Multi Stream Transport controller
│ │     Current version:  05.07.01
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 6 minutes
│ │     GUID:             89fec0b6-6b76-5008-b82c-5e5c6c164007 ← MST-panamera-vmm5331-259
│ │     Device Flags:     • Updatable
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │   
│ └─Embedded Controller:
│       Device ID:        cf294bf55b333004beb7c41f952c1838c23e1f4a
│       Summary:          USB4 controller
│       Current version:  38.0
│       Vendor:           Dell Inc. (USB:0x8087, TBT:0x00D4)
│       Install Duration: 46 seconds
│       GUID:             bd79ce60-525b-5f39-a3f6-c98c495039ff ← TBT-00d4b071
│       Device Flags:     • Updatable
│                         • Device stages updates
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│     
├─Unknown Device:
│     Device ID:          63223cc2d1b0b8d4c45ef8cedcb1f45315d3ff20
│     GUID:               ca5c154c-a46a-59d8-bf77-0ca40522cc85 ← GPIO\ID_INT34C5:00
│   
├─11th Gen Intel Core™ i7-1185G7 @ 3.00GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000ac
│     Vendor:             Intel
│     GUIDs:              2347ad97-b545-5bae-b6b3-b70a9553cbba ← CPUID\PRO_0&FAM_06&MOD_8C
│                         1df99df5-22f4-5505-98cc-22dcc53b132a ← CPUID\PRO_0&FAM_06&MOD_8C&STP_1
│     Device Flags:       • Internal device
│   
├─BIOS:
│     Device ID:          b04e387fb80d2b91f37a4d0c7b21461c451775e1
│     Summary:            Memory Technology Device
│     Vendor:             DMI:Dell Inc.
│     GUIDs:              af783c5c-0390-55a5-ac35-7a6c43c6dbec ← MTD\NAME_BIOS
│                         9075b214-df4f-5c9a-8a1f-569d8e7b39c9 ← MTD\VENDOR_Dell-Inc.&NAME_BIOS
│                         0f205489-9a66-5802-b310-f8f8320d29cf ← MTD\VENDOR_Dell-Inc.&PRODUCT_XPS-13-9310&NAME_BIOS
│     Device Flags:       • Internal device
│                         • Needs a reboot after installation
│                         • Cryptographic hash verification is available
│   
├─Embedded Controller:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    0.0.0.172
│     Minimum Version:    0.0.0.172
│     Vendor:             Dell (DMI:Dell Inc.)
│     Update State:       Success
│     GUID:               176e090d-0ddb-495e-8173-bc998ccfecd0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Embedded Controller:
│     Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
│     Summary:            UEFI ESRT device
│     Current version:    16.112.65.4
│     Minimum Version:    16.112.65.4
│     Vendor:             Dell (DMI:Dell Inc.)
│     Update State:       Success
│     GUID:               558810bc-de64-11e8-9f32-f2801f1b9fd1
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─KXG60PNV2T04 NVMe KIOXIA 2048GB:
│     Device ID:          71b677ca0f1bc2c5b804fa1d59e52064ce589293
│     Summary:            NVM Express solid state drive
│     Current version:    10704104
│     Vendor:             Toshiba Corporation (NVME:0x1179)
│     Serial Number:      Z0LF305KFSH1
│     GUIDs:              73a0c81f-2555-56a5-bb6a-c2aeab2213d1 ← STORAGE-DELL-108638
│                         558810bc-de64-11e8-9f32-f2801f1b9fd1
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│   
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    0.3.18.0
│ │   Minimum Version:    0.3.18.0
│ │   Vendor:             Dell (DMI:Dell Inc.)
│ │   Update State:       Success
│ │   GUID:               cfb08d7c-8d3d-41b1-846b-48f634dfac9d
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ ├─BootGuard Configuration:
│ │     Device ID:        b0d4430dfa6bde9f0c22680df36dbc8c15c80753
│ │     Current version:  20
│ │     Vendor:           Intel Corporation (MEI:0x8086)
│ │     GUIDs:            dd17041c-09ea-4b17-a271-5b989867ec65
│ │                       f18c7464-aa01-5b3d-bd4f-6623597d0f70 ← MEI\VEN_8086&DEV_A0E0
│ │                       2eccc4e8-74e2-5570-adb3-d28c998222d5 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_10280A43
│ │     Device Flags:     • Internal device
│ │   
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  421
│       Minimum Version:  421
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            4a6cd2cb-8741-5257-9d1f-89a275dacca7 ← UEFI\CRT_E28D59CA489BD2AD580F2EA5D62D6A29BB9C02AE5A818434A37DA7FC11DFF9E9&ARCH_X64
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
│     
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Current version:    1.257.0.0
│     Vendor:             ST Microelectronics (TPM:STM)
│     GUIDs:              84df3581-f896-54d2-bd1a-372602f04c32 ← TPM\VEN_STM&DEV_0001
│                         bfaed10a-bbc1-525b-a329-35da2f63e918 ← TPM\VEN_STM&MOD_
│                         70b7b833-7e1a-550a-a291-b94a12d0f319 ← TPM\VEN_STM&DEV_0001&VER_2.0
│                         06f005e9-cb62-5d1a-82d9-13c534c53c48 ← TPM\VEN_STM&MOD_&VER_2.0
│                         fd112308-8a5f-5c8e-9e89-1a8df757f4a1 ← 0a43-2.0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device can recover flash failures
│                         • Full disk encryption secrets may be invalidated when updating
│                         • Signed Payload
│   
├─TigerLake-LP GT2 [Iris Xe Graphics]:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    01
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              54ff3ed7-1ea3-5279-975f-93c13bf2aa53 ← PCI\VEN_8086&DEV_9A49
│                         cacbaa49-f718-59c4-a110-1bc570d4f31c ← PCI\VEN_8086&DEV_9A49&SUBSYS_10280A43
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
├─UEFI Platform Key:
│     Device ID:          6924110cde4fa051bfdc600a60620dc7aa9d3c6a
│     Summary:            Dell Inc. Platform Key
│     Vendor:             Dell Inc.
│     GUID:               5f7cc4ea-9f7a-5c5f-b535-dfbcc73f5ba6 ← UEFI\CRT_2493B118EABD632FD3BA49C333A8329B1982E872
│   
└─Unifying Receiver:
      Device ID:          1bf177ee2510c9dcbe9fa4cb630af962633789e2
      Summary:            Miniaturised USB wireless receiver
      Current version:    RQR12.11_B0032
      Bootloader Version: BOT01.04_B0016
      Vendor:             HIDRAW:0x046D|USB:0x046D
      Install Duration:   30 seconds
      GUIDs:              9d131a0c-a606-580f-8eda-80587250b8d6
                          279ed287-3607-549e-bacc-f873bb9838c4 ← HIDRAW\VEN_046D&DEV_C52B
      Device Flags:       • Updatable
                          • Signed Payload
    
```

</details>

**Additional questions**

- Operating system and version: Ubuntu 22.04
- Have you tried rebooting? Yes.
- Is this a regression? Yes.

**Comment by hughsie** [comment]
> request org.freedesktop.fwupd.request.remove-replug is not a GENERIC_MESSAGE and the device does not set FWUPD_REQUEST_FLAG_NON_GENERIC_MESSAGE

For this, I've pushed 08264f58f5dfe2178cc0968da197fb24197a397a -- can you re-pull and rebuild and get the new warning please.

> invalid cast from 'GUnixInputStream' to 'GSeekable'

For this, can you set `G_DEBUG=fatal-criticals` and then get me a backtrace of where it crashes please.

**Comment by CragW** [comment]
> For this, I've pushed [08264f5](https://github.com/fwupd/fwupd/commit/08264f58f5dfe2178cc0968da197fb24197a397a) -- can you re-pull and rebuild and get the new warning please.

New screen output:
```
$ ./dist/fwupdmgr.sh install ~/Downloads/cab/b1275193349c3ebd1db3821462143ac859302afe3572060fab7ee4793b4892bd-DellDockFirmwareUpdateLinux_01.00.16.cab --allow-reinstall
WARNING: This package has not been validated, it may not work properly.
Decompressing…           [                                       ]
request org.freedesktop.fwupd.request.remove-replug is not a GENERIC_MESSAGE and device cc4b0e729e344517c4690908fe1b4aaadea014ac [dell_dock] does not set FWUPD_REQUEST_FLAG_NON_GENERIC_MESSAGE
```


> For this, can you set `G_DEBUG=fatal-criticals` and then get me a backtrace of where it crashes please.

[fatal-criticals.txt](https://github.com/fwupd/fwupd/files/13809075/fatal-criticals.txt)

It failed to cast `stream` as is a `GInputStream`. 
https://github.com/fwupd/fwupd/blob/main/libfwupdplugin/fu-input-stream.c#L300

**Comment by hughsie** [comment]
> It failed to cast stream as is a GInputStream.
> https://github.com/fwupd/fwupd/blob/main/libfwupdplugin/fu-input-stream.c#L300

Can you paste the backtrace please, you can use `bt<enter>` in the gdb prompt to get it. Thanks.

**Comment by CragW** [comment]
> Can you paste the backtrace please, you can use `bt<enter>` in the gdb prompt to get it. Thanks.

Does this help?

libfwupdplugin.so!fu_input_stream_read_byte_array(GInputStream * stream, gsize offset, gsize count, GError ** error) (/home/crabx/mywork/fwupd/libfwupdplugin/fu-input-stream.c:310)
libfwupdplugin.so!fu_input_stream_read_bytes(GInputStream * stream, gsize offset, gsize count, GError ** error) (/home/crabx/mywork/fwupd/libfwupdplugin/fu-input-stream.c:350)
libfwupdplugin.so!fu_bytes_get_contents_fd(gint fd, gsize count, GError ** error) (/home/crabx/mywork/fwupd/libfwupdplugin/fu-bytes.c:123)
fu_daemon_daemon_method_call(GDBusConnection * connection, const gchar * sender, const gchar * object_path, const gchar * interface_name, const gchar * method_name, GVariant * parameters, GDBusMethodInvocation * invocation, gpointer user_data) (/home/crabx/mywork/fwupd/src/fu-daemon.c:1892)
libgio-2.0.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libglib-2.0.so.0!g_main_context_dispatch (Unknown Source:0)
libglib-2.0.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libglib-2.0.so.0!g_main_loop_run (Unknown Source:0)
fu_daemon_start(FuDaemon * self) (/home/crabx/mywork/fwupd/src/fu-daemon.c:66)
main(int argc, char ** argv) (/home/crabx/mywork/fwupd/src/fu-main.c:218)

**Comment by hughsie** [comment]
> Does this help?

It does! Can you try main now please? I merged `wip/hughsie/parse-stream` which replaces that code completely.

**Comment by CragW** [comment]
> It does! Can you try main now please? I merged `wip/hughsie/parse-stream` which replaces that code completely.

The critical errors in daemon are gone from `main` branch, cheers.

> request org.freedesktop.fwupd.request.remove-replug is not a GENERIC_MESSAGE and the device does not set FWUPD_REQUEST_FLAG_NON_GENERIC_MESSAGE

Non-generic-message is the last issue, #6591 doesn't fix it yet, BTW this error happens to developer build only.

If it is a supported build, then the update messages are prompted okay:

```
$ ./dist/fwupdmgr.sh install ~/Downloads/cab/b1275193349c3ebd1db3821462143ac859302afe3572060fab7ee4793b4892bd-DellDockFirmwareUpdateLinux_01.00.16.cab --allow-reinstall
Waiting…                 [***************************************] Less than one minute remaining…
Successfully installed firmware
The update will continue when the device USB cable has been unplugged.
The update will continue when the device USB cable has been unplugged.
The update will continue when the device USB cable has been unplugged.
The update will continue when the device USB cable has been unplugged.
The update will continue when the device USB cable has been unplugged.
```

**Comment by hughsie** [comment]
@CragW can you edit `libfwupdplugin/fu-device.c` and add something like:

	@@ -5921,6 +5921,7 @@ fu_device_emit_request(FuDevice *self, FwupdRequest *request, FuProgress *progre
		}
		if (!fwupd_request_has_flag(request, FWUPD_REQUEST_FLAG_ALLOW_GENERIC_MESSAGE) &&
		    !fu_device_has_request_flag(self, FWUPD_REQUEST_FLAG_NON_GENERIC_MESSAGE)) {
	+               g_error("HERE");
			g_set_error(error,
				    G_IO_ERROR,
				    G_IO_ERROR_NOT_SUPPORTED,

and then get the backtrace from gdb please.

**Comment by CragW** [comment]
> g_error("HERE");

[update-message.txt](https://github.com/fwupd/fwupd/files/13810132/update-message.txt)


libglib-2.0.so.0!g_logv (Unknown Source:0)
libglib-2.0.so.0!g_log (Unknown Source:0)
libfwupdplugin.so!fu_device_emit_request(FuDevice * self, FwupdRequest * request, FuProgress * progress, GError ** error) (/home/crabx/mywork/fwupd/libfwupdplugin/fu-device.c:5924)
libfwupdplugin.so!fu_device_write_firmware(FuDevice * self, GInputStream * stream, FuProgress * progress, FwupdInstallFlags flags, GError ** error) (/home/crabx/mywork/fwupd/libfwupdplugin/fu-device.c:4466)
libfwupdplugin.so!fu_plugin_device_write_firmware(FuPlugin * self, FuDevice * device, GInputStream * stream, FuProgress * progress, FwupdInstallFlags flags, GError ** error) (/home/crabx/mywork/fwupd/libfwupdplugin/fu-plugin.c:786)
libfwupdplugin.so!fu_plugin_runner_write_firmware(FuPlugin * self, FuDevice * device, GInputStream * stream, FuProgress * progress, FwupdInstallFlags flags, GError ** error) (/home/crabx/mywork/fwupd/libfwupdplugin/fu-plugin.c:2151)
libfwupdengine.so!fu_engine_write_firmware(FuEngine * self, const gchar * device_id, GInputStream * stream_fw, FuProgress * progress, FwupdInstallFlags flags, GError ** error) (/home/crabx/mywork/fwupd/src/fu-engine.c:3202)
libfwupdengine.so!fu_engine_install_blob(FuEngine * self, FuDevice * device, GInputStream * stream_fw, FuProgress * progress, FwupdInstallFlags flags, FwupdFeatureFlags feature_flags, GError ** error) (/home/crabx/mywork/fwupd/src/fu-engine.c:3383)
libfwupdengine.so!fu_engine_install_release(FuEngine * self, FuRelease * release, GInputStream * stream, FuProgress * progress, FwupdInstallFlags flags, GError ** error) (/home/crabx/mywork/fwupd/src/fu-engine.c:2403)
libfwupdengine.so!fu_engine_install_releases(FuEngine * self, FuEngineRequest * request, GPtrArray * releases, FuCabinet * cabinet, FuProgress * progress, FwupdInstallFlags flags, GError ** error) (/home/crabx/mywork/fwupd/src/fu-engine.c:1885)
fu_daemon_authorize_install_queue(FuMainAuthHelper * helper_ref) (/home/crabx/mywork/fwupd/src/fu-daemon.c:794)
fu_daemon_authorize_install_cb(GObject * source, GAsyncResult * res, gpointer user_data) (/home/crabx/mywork/fwupd/src/fu-daemon.c:751)
libgio-2.0.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libfwupdengine.so!fu_polkit_authority_check_cb(GObject * source_object, GAsyncResult * res, gpointer user_data) (/home/crabx/mywork/fwupd/src/fu-polkit-authority.c:75)
libgio-2.0.so.0!g_simple_async_result_complete (Unknown Source:0)
libpolkit-gobject-1.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libglib-2.0.so.0!g_main_context_dispatch (Unknown Source:0)
libglib-2.0.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libglib-2.0.so.0!g_main_loop_run (Unknown Source:0)
fu_daemon_start(FuDaemon * self) (/home/crabx/mywork/fwupd/src/fu-daemon.c:70)

**Comment by hughsie** [comment]
Ahh of course! Can you re-pull wip/hughsie/legacy-generic-message and try again please.

**Comment by CragW** [comment]
> Ahh of course! Can you re-pull wip/hughsie/legacy-generic-message and try again please.

It works! We have a clean table!

**Comment by superm1** [comment]
should have closed with e035a7a
