### ISSUE TITLE
fwupdmgr offers update for a Quectel modem, which already has that firmware, but with weird numbering scheme?

### ISSUE THREAD

**Issue by verpejas** [fwupd/fwupd#9320]
**Describe the bug**

As I understand the modem already has EM061KGLAAR01A02M2G_01.015 but fwupd offers EM061KGLAAR01A02M2G_01.015.01.015 so the same firmware with duplicated version ending? It has been showing up for a month constantly. 
```

Refreshing fwupdmgr firmware update database...
Updating lvfs
Downloading…             [***                                    ]
Successfully downloaded new metadata:
 • 21 devices are updatable
 • 5 devices are supported in the enabled remotes (an update has been published)
Devices with no available firmware updates: 
 • Integrated Camera
 • KEK CA
 • KEK CA
 • Prometheus (IOTA Config)
 • SBAT
 • SSD 990 EVO Plus 2TB
 • ThinkPad Product CA
 • UEFI CA
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • Windows UEFI CA
Devices with the latest available firmware version:
 • Prometheus
 • System Firmware
 • UEFI CA
 • UEFI dbx
LENOVO 21MDS30F00
│
└─EM061K-GL:
  │   Device ID:          665385ef5d3b09dad9922b3ec07bc0b1e0b7b122
  │   Summary:            Mobile broadband device
  │   Current version:    EM061KGLAAR01A02M2G_01.015
  │   Vendor:             Quectel (USB:0x2C7C)
  │   GUIDs:              2bdac371-5939-5239-9dfa-eb4d4ff12bc8 ← USB\VID_2C7C&PID_6008
  │                       e307a004-f1d0-5e6b-9176-b38687fad115 ← USB\VID_2C7C&PID_6008&REV_0504
  │                       cd463d92-6149-5a90-b63e-c75463b485ef ← USB\VID_2C7C&PID_6008&CARRIER_ROW_GENERIC_3GPP
  │                       8de4c5fc-2ae8-5c18-8c52-847aa764ccc8 ← USB\VID_2C7C&PID_6008&REV_0504&CARRIER_ROW_GENERIC_3GPP
  │   Device Flags:       • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Unsigned Payload
  │                       • Can tag for emulation
  │ 
  └─EM061KGL Device Update:
        New version:      EM061KGLAAR01A02M2G_01.015.01.015
        Remote ID:        lvfs
        Release ID:       112135
        Summary:          Firmware for the Quectel EM061KGL modem
        License:          Proprietary
        Size:             83.1 MB
        Created:          2025-04-29 00:00:00
        Urgency:          High
          Tested:         2025-04-30 00:00:00
          Distribution:   ubuntu 24.04
          Old version:    EM061KGLAAR01A02M2G_01.014.01.014
          Version[fwupd]: 1.9.16
        Vendor:           Lenovo
        Release Flags:    • Trusted metadata
                          • Is upgrade
                          • Tested by trusted vendor
        Description:      
        Firmware release EM061KGLAAR01A02M2G_01.015.01.015 packaged for LVFS.
        
        • Performance improvements
        • Stability improvements
        Checksum:         d81ba1913b5b7c898f06020d85fe0a7b6d322d94de390e817906c377437543f3
      

```

**Steps to Reproduce**
Update using fwupdmgr get-updates and then update

**Expected behavior**
Either no update shows or the update succeeds.

**fwupd version information**
Please provide the version of the daemon and client.

```shell
verpejas@ThinkPad-T14-G5-AMD:~$ sudo fwupdtool get-report-metadata
Waiting…                 [*************************************  ]22:53:30.488 FuDeviceLocker       failed to close device: cannot close device, refcount already zero

BatteryLevel:           71
BatteryThreshold:       25
BootTime:               1759358775
CompileVersion(com.hughsie.libjcat): 0.2.3
CompileVersion(com.hughsie.libxmlb): 0.3.24
CompileVersion(info.libusb): 1.0.29
CompileVersion(org.freedesktop.Passim): 0.1.10
CompileVersion(org.freedesktop.fwupd): 2.0.16
CpuArchitecture:        x86_64
CpuModel:               AMD Ryzen 7 PRO 8840U w/ Radeon 780M Graphics
DisplayState:           connected
DistroId:               fedora
DistroName:             Fedora Linux
DistroPrettyName:       Fedora Linux 42 (KDE Plasma Desktop Edition)
DistroVariant:          kde
DistroVersion:          42
EfivarsNvramFree:       125240
EfivarsNvramUsed:       66251
FwupdSupported:         True
HostBaseboardManufacturer: LENOVO
HostBaseboardProduct:   21MDS30F00
HostBiosMajorRelease:   01
HostBiosMinorRelease:   10
HostBiosVendor:         LENOVO
HostBiosVersion:        R2LET35W (1.16 )
HostEnclosureKind:      a
HostFamily:             ThinkPad T14 Gen 5
HostFirmwareMajorRelease: 01
HostFirmwareMinorRelease: 0b
HostProduct:            21MDS30F00
HostSku:                LENOVO_MT_21MD_BU_Think_FM_ThinkPad T14 Gen 5
HostVendor:             LENOVO
KernelCmdline:          nohibernate amdgpu.abmlevel=0
KernelName:             Linux
KernelVersion:          6.16.8-200.fc42.x86_64
LidState:               open
PassimDownloadSaving:   1660128
PlatformArchitecture:   x86_64
PowerState:             ac
RuntimeVersion(com.hughsie.libjcat): 0.2.3
RuntimeVersion(com.hughsie.libxmlb): 0.3.24
RuntimeVersion(org.freedesktop.fwupd): 2.0.16
RuntimeVersion(org.freedesktop.fwupd-efi): 1.6
RuntimeVersion(org.kernel): 6.16.8-200.fc42.x86_64
SELinux:                enforcing
DeviceId:               085a06a30c88261f343dac2f90604805cc01ce4b
  pre:
      CapsuleApplyMethod: nvram
      EspKind:          c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      EspPath:          /boot/efi
      MissingCapsuleHeader: False
  post:
      LastAttemptStatus: 0x0
      LastAttemptVersion: 0x0
DeviceId:               88fc9437af8136bef0aa55342982271060017196
  pre:
      CapsuleApplyMethod: nvram
      EspKind:          c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      EspPath:          /boot/efi
      MissingCapsuleHeader: False
  post:
      LastAttemptStatus: 0x0
      LastAttemptVersion: 0x0
DeviceId:               ee0b555dba08a5790223cf040acb39f05fc7d808
  pre:
      CapsuleApplyMethod: nvram
      EspKind:          c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      EspPath:          /boot/efi
      MissingCapsuleHeader: False
  post:
      LastAttemptStatus: 0x0
      LastAttemptVersion: 0x0
DeviceId:               6f0c4a0cc2cd035c45fece35226e4aaafc449cd5
  pre:
      CapsuleApplyMethod: nvram
      EspKind:          c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      EspPath:          /boot/efi
      MissingCapsuleHeader: False
  post:
      LastAttemptStatus: 0x0
      LastAttemptVersion: 0x0
DeviceId:               bede098fde861317d555511f082f412aa2285b09
  pre:
      CapsuleApplyMethod: nvram
      EspKind:          c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      EspPath:          /boot/efi
      MissingCapsuleHeader: False
  post:
      LastAttemptStatus: 0x0
      LastAttemptVersion: 0x0
DeviceId:               808a73650f2c26f1b7d04ddb954fb29e7a83b752
  pre:
      CapsuleApplyMethod: nvram
      EspKind:          c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      EspPath:          /boot/efi
      MissingCapsuleHeader: False
  post:
      LastAttemptStatus: 0x0
      LastAttemptVersion: 0x0
DeviceId:               e41d56cd59136a5ca480fac4253f9dccc6573d25
  pre:
      CapsuleApplyMethod: nvram
      EspKind:          c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      EspPath:          /boot/efi
      MissingCapsuleHeader: False
  post:
      LastAttemptStatus: 0x0
      LastAttemptVersion: 0x0
DeviceId:               bd31361f2b555ed2a01c402fd3bc20fad5d12aef
  pre:
      CapsuleApplyMethod: nvram
      EspKind:          c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      EspPath:          /boot/efi
      MissingCapsuleHeader: False
  post:
      LastAttemptStatus: 0x0
      LastAttemptVersion: 0x0
  linux_lockdown:
      LinuxLockdown:    integrity
  tpm:
      Pcr0_SHA256:      ac893186da0065449c0583f94088ab6ef98d2a8f7e8da667b6cafb483aba0137
      TpmEventLog:      0x00000008 2ef3c1f342b66b4938dc9aabf964ffd850dd036d5bc194e9a370e0ef4188156d [UgAyAEwARQBUADMANQBXACAAAAA=]
      0x80000008 21d68e22bfda1e80b0e621b325ec840d04e61a0420678a3d523ebe2ad9f85193 [AADACQAAAAAAAB4AAAAAAA==]
      0x80000008 6a6ce73fb1cc0262a96ae58599745a6fa1a3731f2d08af1de25c3f3e7522ec9a [AKDz/wAAAADwAgAAAAAAAA==]
      0x80000008 4101ac3e6a69eaa8aef8f586fd69a704dd23629dba8e7eb625a801e83d7d48ee [AKCX/wAAAAAwOVAAAAAAAA==]
      0x00000001 260e61c6434e72e34823716943afea42c7bc7fae53d70f02f99a6755c713f1cb [QUNQSSBEQVRB]
      0x00000001 608072d8953921f15718897cbb0a47623e0c29fa7286d20beb0d733756acb643 [QUNQSSBEQVRB]
      0x00000004 df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119 [AAAAAA==]
      PCR0: ac893186da0065449c0583f94088ab6ef98d2a8f7e8da667b6cafb483aba0137
      TpmFamily:        2.0
  uefi_pk:
      UefiPkKeyId:      b3774bc6c8b48919dd686e9caeb68af6de0b4ed9
  uefi_capsule:
      BootMgrDesc:      legacy
      BootloaderSupportsFwupd: False
      SecureBoot:       Enabled
      UEFIUXCapsule:    Enabled

verpejas@ThinkPad-T14-G5-AMD:~$ fwupdtool hwids
Loading…                 [**                                     ]
Computer Information
--------------------
BiosVendor: LENOVO
BiosVersion: R2LET35W (1.16 )
Manufacturer: LENOVO
Family: ThinkPad T14 Gen 5
ProductName: 21MDS30F00
ProductSku: LENOVO_MT_21MD_BU_Think_FM_ThinkPad T14 Gen 5
EnclosureKind: 10
BaseboardManufacturer: LENOVO
BaseboardProduct: 21MDS30F00
Hardware IDs
------------
not available as 'BiosMajorRelease' unknown
not available as 'BiosMajorRelease' unknown
not available as 'BiosMajorRelease' unknown
{457b1671-8ab3-5975-b58e-be4f83ee882c}   <- Manufacturer + Family + ProductName + ProductSku + BaseboardManufacturer + BaseboardProduct
{a867ffc0-47c6-533d-b05c-c93e037cd43a}   <- Manufacturer + Family + ProductName + ProductSku
{0ba8c79b-50cd-58c7-98f5-b0d5ff1441b5}   <- Manufacturer + Family + ProductName
{7848da40-fae0-5b1a-a6b1-b790ba1ae3d0}   <- Manufacturer + ProductSku + BaseboardManufacturer + BaseboardProduct
{91fc439d-3a1c-5408-a247-26de082ab3d6}   <- Manufacturer + ProductSku
{ac0719d1-6f43-55f0-a2a8-88dee28b4763}   <- Manufacturer + ProductName + BaseboardManufacturer + BaseboardProduct
{a2435655-8817-5e11-86c3-666356c3bc62}   <- Manufacturer + ProductName
{06704eaf-8f0b-59a7-9d2c-e96f6507b57e}   <- Manufacturer + Family + BaseboardManufacturer + BaseboardProduct
{98cdfff4-7481-590c-9110-1e1570cb3a8c}   <- Manufacturer + Family
{5e820764-888e-529d-a6f9-dfd12bacb160}   <- Manufacturer + EnclosureKind
{a8bca29e-6c66-524a-a80a-19c6c21ee3f1}   <- Manufacturer + BaseboardManufacturer + BaseboardProduct
{6de5d951-d755-576b-bd09-c5cf66b27234}   <- Manufacturer
Extra Hardware IDs
------------------
{47e0559a-b034-589a-a6ae-a05eb8beb182}   <- Manufacturer + Family + ProductName + ProductSku + BiosVendor
{aec1cd90-db8b-51b0-94b6-f6b6e638d181}   <- Manufacturer + Family + ProductName + BiosVendor
{99431f53-09a1-5869-be79-65e2fa3f341d}   <- Manufacturer + BiosVendor
verpejas@ThinkPad-T14-G5-AMD:~$ 

```

**Comment by ConiKost** [comment]
I can confirm the same issue here. ThinkPad T14 Gen 5.

```
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade EM061K-GL from EM061KGLAAR01A02M2G_01.015 to                         ║
║ EM061KGLAAR01A02M2G_01.015.01.015?                                           ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Firmware release EM061KGLAAR01A02M2G_01.015.01.015 packaged for LVFS.        ║
║                                                                              ║
║ • Performance improvements                                                   ║
║ • Stability improvements                                                     ║
║                                                                              ║
║ EM061K-GL and all connected devices may not be usable while updating.        ║
╚══════════════════════════════════════════════════════════════════════════════╝
```

**Comment by verpejas** [comment]
Along with the Quectel issue, today an upgrade to the TPM firmware for the T14 G5 amd was released, supposedly by Gygabyte with Lenovo DMI? The upgrade started well, it said its complete, then rebooted to complete installation. fwupd said its installing system upgrade, then did a reset, and after booting back up i got these:

Devices that were not updated correctly:
 • TPM (0x07020400 → 0x07020401)
Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Review and upload report now? (Requires internet connection) [Y|n]: 

<details>
 <summary>update log - expand to read</summary>
`
Review and upload report now? (Requires internet connection) [Y|n]: y
Target:                  https://fwupd.org/lvfs/firmware/report
Payload:                 {
                           "ReportType" : "history",
                           "ReportVersion" : 2,
                           "MachineId" : "4268b67fc430268937245181bc214d3c2739bf4394de106e55ce2aa1d6c1000e",
                           "Metadata" : {
                             "CompileVersion(info.libusb)" : "1.0.29",
                             "HostBiosMinorRelease" : "10",
                             "CompileVersion(org.freedesktop.fwupd)" : "2.0.16",
                             "HostFirmwareMinorRelease" : "0b",
                             "DistroId" : "fedora",
                             "HostBaseboardProduct" : "21MDS30F00",
                             "CompileVersion(com.hughsie.libxmlb)" : "0.3.24",
                             "CompileVersion(org.freedesktop.Passim)" : "0.1.10",
                             "KernelCmdline" : "nohibernate amdgpu.abmlevel=0",
                             "EfivarsNvramUsed" : "66619",
                             "CompileVersion(com.hughsie.libjcat)" : "0.2.3",
                             "HostBiosVendor" : "LENOVO",
                             "PlatformArchitecture" : "x86_64",
                             "HostBiosMajorRelease" : "01",
                             "DisplayState" : "connected",
                             "HostBaseboardManufacturer" : "LENOVO",
                             "EfivarsNvramFree" : "82948",
                             "CpuModel" : "AMD Ryzen 7 PRO 8840U w/ Radeon 780M Graphics",
                             "KernelName" : "Linux",
                             "BootTime" : "1759998518",
                             "HostProduct" : "21MDS30F00",
                             "HostFirmwareMajorRelease" : "01",
                             "RuntimeVersion(org.freedesktop.fwupd-efi)" : "1.6",
                             "BatteryThreshold" : "25",
                             "RuntimeVersion(com.hughsie.libxmlb)" : "0.3.24",
                             "LidState" : "open",
                             "DistroVariant" : "kde",
                             "FwupdSupported" : "True",
                             "RuntimeVersion(com.hughsie.libjcat)" : "0.2.5",
                             "DistroName" : "Fedora Linux",
                             "DistroPrettyName" : "Fedora Linux 42 (KDE Plasma Desktop Edition)",
                             "RuntimeVersion(org.freedesktop.Passim)" : "0.1.10",
                             "PowerState" : "ac",
                             "KernelVersion" : "6.16.10-200.fc42.x86_64",
                             "HostVendor" : "LENOVO",
                             "HostBiosVersion" : "R2LET35W (1.16 )",
                             "HostFamily" : "ThinkPad T14 Gen 5",
                             "PassimDownloadSaving" : "1660128",
                             "BatteryLevel" : "59",
                             "CpuArchitecture" : "x86_64",
                             "RuntimeVersion(org.kernel)" : "6.16.10-200.fc42.x86_64",
                             "RuntimeVersion(org.freedesktop.fwupd)" : "2.0.16",
                             "DistroVersion" : "42",
                             "SELinux" : "enforcing",
                             "HostSku" : "LENOVO_MT_21MD_BU_Think_FM_ThinkPad T14 Gen 5",
                             "HostEnclosureKind" : "a"
                           },
                           "Reports" : [
                             {
                               "Checksum" : "7d0aafd587bfd776fd337a56150d2c94d4298a4ab64cad77d53d01a302af4198",
                               "ReleaseId" : "129075",
                               "Protocol" : "org.uefi.capsule",
                               "UpdateState" : 3,
                               "UpdateError" : "failed to run update on reboot: expected 0x07020401 and got 0x07020400",
                               "Guid" : [
                                 "0eb9bda9-3010-493a-a6a8-b5e80eddf870"
                               ],
                               "Plugin" : "uefi_capsule",
                               "VersionOld" : "0x07020400",
                               "VersionNew" : "0x07020401",
                               "Flags" : 140738029420843,
                               "Created" : 1759996683,
                               "Modified" : 1759998300,
                               "Metadata" : {
                                 "DistroVariant" : "kde",
                                 "UEFIUXCapsule" : "Enabled",
                                 "HostFamily" : "ThinkPad T14 Gen 5",
                                 "HostSku" : "LENOVO_MT_21MD_BU_Think_FM_ThinkPad T14 Gen 5",
                                 "CompileVersion(com.hughsie.libjcat)" : "0.2.3",
                                 "RuntimeVersion(org.freedesktop.fwupd)" : "2.0.16",
                                 "CpuModel" : "AMD Ryzen 7 PRO 8840U w/ Radeon 780M Graphics",
                                 "HostFirmwareMinorRelease" : "0b",
                                 "MissingCapsuleHeader" : "False",
                                 "KernelName" : "Linux",
                                 "CapsuleApplyMethod" : "nvram",
                                 "LidState" : "open",
                                 "DisplayState" : "connected",
                                 "EfivarsNvramFree" : "86060",
                                 "SystemIntegrityOld" : "UEFI:Boot0023=ff0946d23f770f76008cd5c915adb84542adb5b243427fd90c6480f5f356e964\nACPI:TPM2=2169431aabd2fafc6894ec7e737b8062a00fe75a522ac69472dbf5f572580075\nUEFI:Boot0013=ddbd73e828890ac9ed369b619ee13efb1e0fed33d30d40cdbe02e79cf89db246\nUEFI:Boot001D=ee1ebe6bbb8f0ae875f7b14d64d28d81d79930150370a8cd999e2c951afbf131\nUEFI:Boot0019=4f788b9a962d0b3d72611ad96f28c4aa306e122861abbb415b3591cf16e8d3a9\nUEFI:Boot0024=d13efa467b50048657604cd304e3018c21234b5fec18874bb5d8b0a650bb72a7\nUEFI:KEK=3747f80f9731d0364a3bbabffd670383bb1fb63d766bef5db7b5e08e7f5d886d\nUEFI:OsIndications=af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc\nUEFI:Boot0014=7ffd8b7c1280ddfb82ae599446bf40376745955bba173bd12ca32e189b1de153\nUEFI:SignatureSupport=7579884c3681593cb81401ed6b2d28fe5e0ad4d1ea236821907f94ecace0a3b1\nUEFI:Boot001E=3a9a8abf951e28a794af61f4c7247313e7117261e25ff09c15ac6754f6563897\nUEFI:dbx=f8628a76cc56035395f42f785833f3a3f15bb2cb7570b7679f35ac1c62517630\nACPI:MSDM=6902320cf10ff6b3ba6cfe7ee273c414d233ea2cf5b306263f7ab096f2ed1666\nUEFI:Boot0025=0338bdee3d751827e6eeee95776d4a702b80e975be92ba1f85bee861dc8da07d\nUEFI:Boot0015=d4856aa3fcca0b7be0f37419bcefc81b9f7ab51238e28789a70a10c63df67a20\nUEFI:OsIndicationsSupported=bf5b0e89f1caed18c8d6ff15d17ecc5c6e0c89510b4bc6d7b4b51d4ed30999cb\nUEFI:Boot0020=d80f861ff9de09ce3d9801fcd1c6c3f2f5b972e08ea47188bf6da91d9e3209a3\nUEFI:Boot001F=24ee8e9848df33bcefb876af9950ba111a3dcb24438f1231971f22a2bcd19887\nUEFI:Boot0010=195957a2bdad9c44810b6c2b0568f781f93741990f3c0528154c2754c977a53d\nUEFI:Boot0026=146af59bf8e2f528e5f02b13c349e118a41e8fb60dacb0b8112f5fc3eb0c92ea\nUEFI:Boot0000=afbdc2fe87877ec8c7294c89921aae0ec380754dc319ae3cc0a595bbd15618bd\nUEFI:Boot0016=c1ef380c5009d8dc85fd35ff60c80137536b32d10f3f71427ebf691a1d84ad48\nUEFI:Boot0031=ce2dec4f0f868b5104139ad9eeb26e75c7ca49a7e38f5f082ebfcb70e63987c9\nUEFI:Boot0021=398dd601149fdd93f364bf39eff56eb54fe9cedb07d2b2bd1b1c51dd39e1e5ce\nUEFI:Boot0011=8e2c24e0be75283e36ff129e34a2673182d06be7bacf6d24aaf9b3fde831d5d0\nUEFI:SecureBoot=4bf5122f344554c53bde2ebb8cd2b7e3d1600ad631c385a5d7cce23c7785459a\nUEFI:SetupMode=6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d\nUEFI:PK=34314264f8d787431e19f4dd9584c202afb54943ef0afbf5a737a1ccbbcc07b4\nUEFI:Boot001B=0e395c9c98fa506d57e13c52d1a8ad5aa219507f1e624b38590cb61c98a99d18\nUEFI:Boot0017=a917e9227167d17ceb807593f2c3b4bb68a4480357ce81f45bac18874737c2e6\nUEFI:Boot0001=8818a494e085108b2c33cdbd498b0c6d7abdaa022298fac2abf7525cf3f8065c\nUEFI:VendorKeys=6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d\nUEFI:Boot0022=413c1f5c3f10889a3b1e20349b89f2f66422db9171c29b1ca11aa623d948a74c\nUEFI:Boot0012=c739e24d56b0bfad666ab8028c825550dabf1d701c70ff7c30eeee066e6c5091\nUEFI:db=c4bab66d182b935045e4d805301f574172623c429d58ce7b395b19db0264edb4\nUEFI:BootCurrent=47dc540c94ceb704a23875c11273e16bb0b8a87aed84de911f2133568115f254\nUEFI:Boot001C=5a4b1bdcc8d1479e77823eec1ae65f6c44fe03b6549f83b6dd39a4b3f68b9da9\nUEFI:Boot0018=9894da94e05b08f69c802500399c58670cabcf894df56f7935e3ba581383073b\nUEFI:Boot0002=c73e98e7325c332fa79a9db254c84a42afe324867498814c3862c9ef3f24ad1f",
                                 "Pcr0_SHA256" : "ac893186da0065449c0583f94088ab6ef98d2a8f7e8da667b6cafb483aba0137",
                                 "DistroVersion" : "42",
                                 "EfivarsNvramUsed" : "66251",
                                 "HostBiosMajorRelease" : "01",
                                 "RuntimeVersion(com.hughsie.libxmlb)" : "0.3.24",
                                 "BootTime" : "1759990470",
                                 "RuntimeVersion(org.kernel)" : "6.16.10-200.fc42.x86_64",
                                 "PassimDownloadSaving" : "1660128",
                                 "HostBiosMinorRelease" : "10",
                                 "HostVendor" : "LENOVO",
                                 "CompileVersion(org.freedesktop.Passim)" : "0.1.10",
                                 "RuntimeVersion(org.freedesktop.Passim)" : "0.1.10",
                                 "LinuxLockdown" : "integrity",
                                 "FwupdSupported" : "True",
                                 "RuntimeVersion(org.freedesktop.fwupd-efi)" : "1.6",
                                 "BatteryThreshold" : "25",
                                 "HostBiosVersion" : "R2LET35W (1.16 )",
                                 "EspKind" : "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                                 "LastAttemptStatus" : "0x0",
                                 "BatteryLevel" : "54",
                                 "BootloaderSupportsFwupd" : "False",
                                 "DistroPrettyName" : "Fedora Linux 42 (KDE Plasma Desktop Edition)",
                                 "HostBaseboardProduct" : "21MDS30F00",
                                 "HostBiosVendor" : "LENOVO",
                                 "SecureBoot" : "Enabled",
                                 "CompileVersion(com.hughsie.libxmlb)" : "0.3.24",
                                 "CpuArchitecture" : "x86_64",
                                 "SystemIntegrityNew" : "UEFI:Boot0023=ff0946d23f770f76008cd5c915adb84542adb5b243427fd90c6480f5f356e964\nACPI:TPM2=2169431aabd2fafc6894ec7e737b8062a00fe75a522ac69472dbf5f572580075\nUEFI:Boot0013=ddbd73e828890ac9ed369b619ee13efb1e0fed33d30d40cdbe02e79cf89db246\nUEFI:Boot001D=ee1ebe6bbb8f0ae875f7b14d64d28d81d79930150370a8cd999e2c951afbf131\nUEFI:Boot0019=4f788b9a962d0b3d72611ad96f28c4aa306e122861abbb415b3591cf16e8d3a9\nUEFI:Boot0024=d13efa467b50048657604cd304e3018c21234b5fec18874bb5d8b0a650bb72a7\nUEFI:KEK=3747f80f9731d0364a3bbabffd670383bb1fb63d766bef5db7b5e08e7f5d886d\nUEFI:OsIndications=af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc\nUEFI:Boot0014=7ffd8b7c1280ddfb82ae599446bf40376745955bba173bd12ca32e189b1de153\nUEFI:SignatureSupport=7579884c3681593cb81401ed6b2d28fe5e0ad4d1ea236821907f94ecace0a3b1\nUEFI:Boot001E=3a9a8abf951e28a794af61f4c7247313e7117261e25ff09c15ac6754f6563897\nUEFI:dbx=f8628a76cc56035395f42f785833f3a3f15bb2cb7570b7679f35ac1c62517630\nACPI:MSDM=6902320cf10ff6b3ba6cfe7ee273c414d233ea2cf5b306263f7ab096f2ed1666\nUEFI:Boot0025=0338bdee3d751827e6eeee95776d4a702b80e975be92ba1f85bee861dc8da07d\nUEFI:Boot0015=d4856aa3fcca0b7be0f37419bcefc81b9f7ab51238e28789a70a10c63df67a20\nUEFI:OsIndicationsSupported=bf5b0e89f1caed18c8d6ff15d17ecc5c6e0c89510b4bc6d7b4b51d4ed30999cb\nUEFI:Boot0020=d80f861ff9de09ce3d9801fcd1c6c3f2f5b972e08ea47188bf6da91d9e3209a3\nUEFI:Boot001F=24ee8e9848df33bcefb876af9950ba111a3dcb24438f1231971f22a2bcd19887\nUEFI:Boot0010=195957a2bdad9c44810b6c2b0568f781f93741990f3c0528154c2754c977a53d\nUEFI:Boot0026=146af59bf8e2f528e5f02b13c349e118a41e8fb60dacb0b8112f5fc3eb0c92ea\nUEFI:Boot0000=afbdc2fe87877ec8c7294c89921aae0ec380754dc319ae3cc0a595bbd15618bd\nUEFI:Boot0016=c1ef380c5009d8dc85fd35ff60c80137536b32d10f3f71427ebf691a1d84ad48\nUEFI:Boot0031=ce2dec4f0f868b5104139ad9eeb26e75c7ca49a7e38f5f082ebfcb70e63987c9\nUEFI:Boot0021=398dd601149fdd93f364bf39eff56eb54fe9cedb07d2b2bd1b1c51dd39e1e5ce\nUEFI:Boot0011=8e2c24e0be75283e36ff129e34a2673182d06be7bacf6d24aaf9b3fde831d5d0\nUEFI:SecureBoot=4bf5122f344554c53bde2ebb8cd2b7e3d1600ad631c385a5d7cce23c7785459a\nUEFI:SetupMode=6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d\nUEFI:PK=34314264f8d787431e19f4dd9584c202afb54943ef0afbf5a737a1ccbbcc07b4\nUEFI:Boot001B=0e395c9c98fa506d57e13c52d1a8ad5aa219507f1e624b38590cb61c98a99d18\nUEFI:Boot0017=a917e9227167d17ceb807593f2c3b4bb68a4480357ce81f45bac18874737c2e6\nUEFI:Boot0001=8818a494e085108b2c33cdbd498b0c6d7abdaa022298fac2abf7525cf3f8065c\nUEFI:VendorKeys=6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d\nUEFI:Boot0022=413c1f5c3f10889a3b1e20349b89f2f66422db9171c29b1ca11aa623d948a74c\nUEFI:Boot0012=c739e24d56b0bfad666ab8028c825550dabf1d701c70ff7c30eeee066e6c5091\nUEFI:db=c4bab66d182b935045e4d805301f574172623c429d58ce7b395b19db0264edb4\nUEFI:BootCurrent=47dc540c94ceb704a23875c11273e16bb0b8a87aed84de911f2133568115f254\nUEFI:Boot001C=5a4b1bdcc8d1479e77823eec1ae65f6c44fe03b6549f83b6dd39a4b3f68b9da9\nUEFI:Boot0018=9894da94e05b08f69c802500399c58670cabcf894df56f7935e3ba581383073b\nUEFI:Boot0002=c73e98e7325c332fa79a9db254c84a42afe324867498814c3862c9ef3f24ad1f",
                                 "CompileVersion(info.libusb)" : "1.0.29",
                                 "PowerState" : "ac",
                                 "RuntimeVersion(com.hughsie.libjcat)" : "0.2.5",
                                 "SELinux" : "enforcing",
                                 "EspPath" : "/boot/efi",
                                 "LastAttemptVersion" : "0x0",
                                 "DistroId" : "fedora",
                                 "HostProduct" : "21MDS30F00",
                                 "TpmEventLog" : "0x00000008 2ef3c1f342b66b4938dc9aabf964ffd850dd036d5bc194e9a370e0ef4188156d [UgAyAEwARQBUADMANQBXACAAAAA=]\n0x80000008 21d68e22bfda1e80b0e621b325ec840d04e61a0420678a3d523ebe2ad9f85193 [AADACQAAAAAAAB4AAAAAAA==]\n0x80000008 6a6ce73fb1cc0262a96ae58599745a6fa1a3731f2d08af1de25c3f3e7522ec9a [AKDz/wAAAADwAgAAAAAAAA==]\n0x80000008 4101ac3e6a69eaa8aef8f586fd69a704dd23629dba8e7eb625a801e83d7d48ee [AKCX/wAAAAAwOVAAAAAAAA==]\n0x00000001 260e61c6434e72e34823716943afea42c7bc7fae53d70f02f99a6755c713f1cb [QUNQSSBEQVRB]\n0x00000001 608072d8953921f15718897cbb0a47623e0c29fa7286d20beb0d733756acb643 [QUNQSSBEQVRB]\n0x00000004 df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119 [AAAAAA==]\nPCR0: ac893186da0065449c0583f94088ab6ef98d2a8f7e8da667b6cafb483aba0137",
                                 "CompileVersion(org.freedesktop.fwupd)" : "2.0.16",
                                 "DistroName" : "Fedora Linux",
                                 "BootMgrDesc" : "legacy",
                                 "TpmFamily" : "2.0",
                                 "HostBaseboardManufacturer" : "LENOVO",
                                 "KernelCmdline" : "nohibernate amdgpu.abmlevel=0",
                                 "KernelVersion" : "6.16.10-200.fc42.x86_64",
                                 "HostFirmwareMajorRelease" : "01",
                                 "PlatformArchitecture" : "x86_64",
                                 "HostEnclosureKind" : "a"
                               }
                             }
                           ]
                         }
Proceed with upload? [Y|n]: 
`
</details>

After a refresh, still both firmware updates are being offered, and both of them fail.
```
LENOVO 21MDS30F00
│
├─EM061K-GL:
│ │   Device ID:          665385ef5d3b09dad9922b3ec07bc0b1e0b7b122
│ │   Summary:            Mobile broadband device
│ │   Current version:    EM061KGLAAR01A02M2G_01.015
│ │   Vendor:             Quectel (USB:0x2C7C)
│ │   GUIDs:              2bdac371-5939-5239-9dfa-eb4d4ff12bc8 ← USB\VID_2C7C&PID_6008
│ │                       e307a004-f1d0-5e6b-9176-b38687fad115 ← USB\VID_2C7C&PID_6008&REV_0504
│ │                       cd463d92-6149-5a90-b63e-c75463b485ef ← USB\VID_2C7C&PID_6008&CARRIER_ROW_GENERIC_3GPP
│ │                       8de4c5fc-2ae8-5c18-8c52-847aa764ccc8 ← USB\VID_2C7C&PID_6008&REV_0504&CARRIER_ROW_GENERIC_3GPP
│ │   Device Flags:       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Unsigned Payload
│ │                       • Can tag for emulation
│ │ 
│ └─EM061KGL Device Update:
│       New version:      EM061KGLAAR01A02M2G_01.015.01.015
│       Remote ID:        lvfs
│       Release ID:       112135
│       Summary:          Firmware for the Quectel EM061KGL modem
│       License:          Proprietary
│       Size:             83.1 MB
│       Created:          2025-04-29 00:00:00
│       Urgency:          High
│         Tested:         2025-04-30 00:00:00
│         Distribution:   ubuntu 24.04
│         Old version:    EM061KGLAAR01A02M2G_01.014.01.014
│         Version[fwupd]: 1.9.16
│       Vendor:           Lenovo
│       Release Flags:    • Trusted metadata
│                         • Is upgrade
│                         • Tested by trusted vendor
│       Description:      
│       Firmware release EM061KGLAAR01A02M2G_01.015.01.015 packaged for LVFS.
│       
│       • Performance improvements
│       • Stability improvements
│       Checksum:         d81ba1913b5b7c898f06020d85fe0a7b6d322d94de390e817906c377437543f3
│     
└─TPM:
  │   Device ID:          6f0c4a0cc2cd035c45fece35226e4aaafc449cd5
  │   Summary:            UEFI System Resource Table device (updated via NVRAM)
  │   Current version:    0x07020400
  │   Vendor:             Gigabyte (DMI:LENOVO)
  │   Update State:       Success
  │   GUID:               0eb9bda9-3010-493a-a6a8-b5e80eddf870
  │   Device Flags:       • Internal device
  │                       • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Needs a reboot after installation
  │                       • Device is usable for the duration of the update
  │                       • Signed Payload
  │   Device Requests:    • Message
  │ 
  └─AITOP ATOM TPM FW FW TPM Update:
        New version:      0x07020401
        Remote ID:        lvfs
        Release ID:       129075
        Summary:          AITOP ATOM Trusted Platform Module Firmware Update
        License:          Proprietary
        Size:             242.7 kB
        Created:          2025-10-08 00:00:00
        Urgency:          High
          Tested:         2025-10-09 00:00:00
          Distribution:   ubuntu 24.04
          Old version:    0x07020400
          Version[fwupd]: 1.9.31
        Vendor:           Gigabyte
        Duration:         30 seconds
        Release Flags:    • Trusted metadata
                          • Is upgrade
                          • Tested by trusted vendor
        Description:      
        This update improves the performance and stability of the AITOP ATOM Trusted Platform Module Device.
        Checksum:         7d0aafd587bfd776fd337a56150d2c94d4298a4ab64cad77d53d01a302af4198
      
```

**Comment by verpejas** [comment]
Seems to be fixed for me - fwupd no longer offers this update as of today. (Yesterday I did a dist-upgrade to Fedora 43, maybe that's why?) I'm still on fwupd-2.0.16.

**Comment by ConiKost** [comment]
I am still getting the firmware update ```EM061KGLAAR01A02M2G_01.015.01.015``` offered, but you don't anymore?

**Comment by verpejas** [comment]
> I am still getting the firmware update `EM061KGLAAR01A02M2G_01.015.01.015` offered, but you don't anymore?

Sorry for late reply. It seems to have been fixed on my end. I was also getting a Gigabyte TPM update alongside Quectel modem update, but 2 weeks ago both of them disappeared and I've had no issues since. All of my devices are showing up correctly as up to date.

**Comment by ConiKost** [comment]
Thank you for your reply. I do wonder, why I am still getting the update. Already tried to force-update the cache. FWICS, you have the exact same modem?

**Comment by verpejas** [comment]
> Thank you for your reply. I do wonder, why I am still getting the update. Already tried to force-update the cache. FWICS, you have the exact same modem?

Yes, i have the exact same modem (EM061K-GL) and i always do a force cache update for fwupd as a part of my standard update script routine. It just stopped showing up, and shows the modem as up to date with firmware EM061KGLAAR01A02M2G_01.015

**Comment by ConiKost** [comment]
It looks like, that this is for me also solved. I am not getting anymore the update offered.
